### ISSUE TITLE
[SOLVED] Instagram update has destroyed the old version of Insomniac and I cannot get the new one running

### ISSUE THREAD

**Issue by Dioxete** [alexal1/Insomniac#130]
I have been using and old version consistently for the past 2 months, but now it seems to be stucked when the bot tries to see the followers so I tried to update to the newest version and I get this error, any clue what is wrong?

python insomniac.py --interact japan_photo_now --follow-percentage 80 --follow-limit 50 --total-likes-limit 70 --repeat 10
'git' is not recognized as an internal or external command,
operable program or batch file.
Insomniac (Work In Progress)

[10/09 11:42:22] Connected devices via adb: 1. That's ok.
[10/09 11:42:22] Instagram version: 162.0.0.42.125
[10/09 11:42:22] Using uiautomator v2
[W 201009 11:42:27 __init__:203] atx-agent has something wrong, auto recovering
[D 201009 11:42:27 __init__:286] device ff2f68c09804 is online
[I 201009 11:42:29 init:155] uiautomator2 version: 2.11.4
Traceback (most recent call last):
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 289, in _prepare_atx_agent
    version = requests.get(version_url, timeout=3).text
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insomniac.py", line 439, in <module>
    main()
  File "insomniac.py", line 47, in main
    device = create_device(args.old, device_id)
  File "C:\Users\di0x\src\device_facade.py", line 13, in create_device
    return DeviceFacade(is_old, device_id)
  File "C:\Users\di0x\src\device_facade.py", line 33, in __init__
    self.deviceV2 = uiautomator2.connect() if device_id is None else uiautomator2.connect(device_id)
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 1820, in connect
    return connect_usb(addr)
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 1861, in connect_usb
    return Device(serial)
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 241, in __init__
    wlan_ip = self.wlan_ip
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 407, in wlan_ip
    ip = self.http.get("/wlan/ip").text.strip()
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 208, in request
    self.__client._prepare_atx_agent()
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 293, in _prepare_atx_agent
    self._setup_atx_agent()
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 303, in _setup_atx_agent
    if not _initer.check_install():
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\init.py", line 306, in check_install
    if d.sync.stat(self.atx_agent_path).size == 0:
  File "C:\Users\di0x\AppData\Local\Programs\Python\Python37\lib\site-packages\adbutils\__init__.py", line 550, in stat
    return FileInfo(mode, size, datetime.datetime.fromtimestamp(mtime),
OSError: [Errno 22] Invalid argument

**Comment by Dioxete** [comment]
[SOLVED]

The problem was with the python version. Not working on the 3.7.0 nor the 3.9.0 got it running with the 3.8.6
