### ISSUE TITLE
Block on Press search 

### ISSUE THREAD

**Issue by jerematt23** [alexal1/Insomniac#14]
tha app open on the phone after it s just show this message on the terminal 

if you can help me thank you 

home2@home2-VirtualBox:~/Insomniac$ python3 insomniac.py --bloggers marco_verratti92
Insomniac v1.2.4

Connected devices via adb: 1. That's ok.
bloggers = marco_verratti92

-------- START: 2020-06-10 16:39:36.630498 --------
Open Instagram app
Sleep for 4 seconds

Handle @marco_verratti92
Press search
Traceback (most recent call last):
  File "/home/home2/.local/lib/python3.8/site-packages/uiautomator/__init__.py", line 438, in wrapper
    return _method_obj(*args, **kwargs)
  File "/home/home2/.local/lib/python3.8/site-packages/uiautomator/__init__.py", line 127, in __call__
    result = urllib2.urlopen(req, timeout=self.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1355, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.8/urllib/request.py", line 1330, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insomniac.py", line 219, in <module>
    main()
  File "insomniac.py", line 49, in main
    _job_handle_bloggers(device, args.bloggers, int(args.likes_count), storage, on_interaction)
  File "insomniac.py", line 90, in _job_handle_bloggers
    handle_blogger(device, blogger, likes_count, storage, _on_like, on_interaction)
  File "/home/home2/Insomniac/action_handle_blogger.py", line 17, in handle_blogger
    _open_user_followers(device, username)
  File "/home/home2/Insomniac/action_handle_blogger.py", line 25, in _open_user_followers
    search_button.click.wait()
  File "/home/home2/.local/lib/python3.8/site-packages/uiautomator/__init__.py", line 76, in __call__
    return self.func(*args, **kwargs)
  File "/home/home2/.local/lib/python3.8/site-packages/uiautomator/__init__.py", line 975, in _click
    return self.jsonrpc.clickAndWaitForNewWindow(self.selector, timeout)
  File "/home/home2/.local/lib/python3.8/site-packages/uiautomator/__init__.py", line 442, in wrapper
    server.start(timeout=30)
  File "/home/home2/.local/lib/python3.8/site-packages/uiautomator/__init__.py", line 498, in start
    raise IOError("RPC server not started!")
OSError: RPC server not started!

**Comment by alexal1** [comment]
Seems like a problem with the connection, not with the script. Try reconnecting your device, check that you've enabled Developer mode and USB debugging. If that doesn't help, try `adb kill-server` or killing adb process, then reconnect again. Also have a look at #2.

**Comment by alexal1** [comment]
I close this issue for now because the problem seems to be local. If there's some new information, feel free to reopen it.
