### ISSUE TITLE
IGer with shop causes crash i suppose

### ISSUE THREAD

**Issue by fp231** [alexal1/Insomniac#146]
Hi Guys,

first of all: what a great project. I experimented with a lot of bots and this one is just great, because it's real. 

But i stumbled on an issue: The bot crashes when an account has got a shop. Cannot find Follow Botton, i suppose because of the Shop Button on top of it. I would love to help, but my python isnt good enough. So here is the error promt:

Cannot find neither Follow button, nor Unfollow button. Maybe not English language is set?
Traceback (most recent call last):
  File "/home/pi/Desktop/instabot/handybot/Insomniac/insomniac.py", line 397, in wrapper
    func(*args, **kwargs)
  File "/home/pi/Desktop/instabot/handybot/Insomniac/insomniac.py", line 203, in job
    on_interaction)
  File "/home/pi/Desktop/instabot/handybot/Insomniac/src/action_handle_blogger.py", line 43, in handle_blogger
    _iterate_over_followers(device, interaction, is_follow_limit_reached, storage, on_interaction, is_myself)
  File "/home/pi/Desktop/instabot/handybot/Insomniac/src/action_handle_blogger.py", line 143, in _iterate_over_followers
    interaction_succeed, followed = interaction(device, username=username, can_follow=can_follow)
  File "/home/pi/Desktop/instabot/handybot/Insomniac/src/action_handle_blogger.py", line 264, in _interact_with_user
    return True, _follow(device, username, follow_percentage)
  File "/home/pi/Desktop/instabot/handybot/Insomniac/src/action_handle_blogger.py", line 346, in _follow
    save_crash(device)
  File "/home/pi/Desktop/instabot/handybot/Insomniac/src/utils.py", line 102, in save_crash
    device.dump_hierarchy("crashes/" + directory_name + "/view_hierarchy" + view_hierarchy_format)
  File "/home/pi/Desktop/instabot/handybot/Insomniac/src/device_facade.py", line 76, in dump_hierarchy
    outfile.write(xml_dump)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0308' in position 11605: ordinal not in range(256)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Desktop/instabot/handybot/Insomniac/insomniac.py", line 439, in <module>
    main()
  File "/home/pi/Desktop/instabot/handybot/Insomniac/insomniac.py", line 109, in main
    on_interaction)
  File "/home/pi/Desktop/instabot/handybot/Insomniac/insomniac.py", line 207, in _job_handle_bloggers
    job()
  File "/home/pi/Desktop/instabot/handybot/Insomniac/insomniac.py", line 420, in wrapper
    save_crash(device)
  File "/home/pi/Desktop/instabot/handybot/Insomniac/src/utils.py", line 102, in save_crash
    device.dump_hierarchy("crashes/" + directory_name + "/view_hierarchy" + view_hierarchy_format)
  File "/home/pi/Desktop/instabot/handybot/Insomniac/src/device_facade.py", line 76, in dump_hierarchy
    outfile.write(xml_dump)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0308' in position 11605: ordinal not in range(256)

![screenshot](https://user-images.githubusercontent.com/69848354/96485279-d7099800-123c-11eb-92b5-dc3380df360d.jpg)

If i can help in any way, let me know. Big Thanks and best regards,
fp

**Comment by cecimascaras** [comment]
the same with me

**Comment by 10000hzl** [comment]
same here

**Comment by soulpawa** [comment]
yes, me too, I notice that in one device, so I guess it's not able to find the button follow and crashes

**Comment by toscan** [comment]
Hey guy, did you find a solution ? On my side, skipping business account did not solve the issue, sometime the bot goes in the account anyway.

**Comment by GitNees** [comment]
You can fix this by launching your script this way 

python -Xutf8 start.py --your commands

**Comment by adchsm** [comment]
I can confirm I'm also receiving this error, which causes an endless loop of error -> settings -> back to user - > error. Running the command above with -Xutf8 didn't fix it either.

**Comment by Fadude** [comment]
Fixed on v3.4.0 - shop-profiles support added
