### ISSUE TITLE
Next item not found: probably reached end of the screen. CRASH

### ISSUE THREAD

**Issue by soulpawa** [alexal1/Insomniac#150]
getting this error a new device
Next item not found: probably reached end of the screen.
[10/22 21:56:20] Need to scroll now
[10/22 21:56:31] Traceback (most recent call last):
  File "/home/pi/Insomniac/src/device_facade.py", line 178, in scroll
    self.viewV2.scroll.toEnd(max_swipes=1)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/_selector.py", line 575, in __call__
    max_swipes, steps)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 435, in __call__
    http_timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 441, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 513, in _jsonrpc_call

[Crash-2020-10-06-22-16-46.zip](https://github.com/alexal1/Insomniac/files/5425794/Crash-2020-10-06-22-16-46.zip)

**Comment by alexal1** [comment]
Fixed in `v3.1.0`
