### ISSUE TITLE
Json Decoder Error Expecting ',' delimiter

### ISSUE THREAD

**Issue by don-ciccio** [alexal1/Insomniac#162]
Hi, I updated to the last version I started the script and everything went fine. After killing the process the first time I keep getting this error:

Traceback (most recent call last):
  File "start.py", line 4, in <module>
    insomniac.run(activation_code)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/__init__.py", line 97, in run
    storage = Storage(session_state.my_username)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/storage.py", line 30, in __init__
    self.interacted_users = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 17263 column 57 (char 533080)

I tried reinstalling insomniac, logging out of the account and switching devices but none of those seem to work. Any ideas why?

**Comment by alexal1** [comment]
Unfortunately, you killed the process while it was writing to `interacted_users.json` file. You can find this file in the `<username>` folder which is in the folder where you launch the script from. You can either simply delete this file, or fix broken brackets (as JSON fromat requires).
