### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u0411' in position 11586: character maps to <undefined>

### ISSUE THREAD

**Issue by yuceltoluyag** [alexal1/Insomniac#165]
```
python start.py  --unfollow-any 1-500
Insomniac v3.1.1

[10/31 23:25:42] Cannot confirm unfollow.
Traceback (most recent call last):
  File "C:\Users\yucel\Insomniac\venv\lib\site-packages\insomniac\__init__.py", line 418, in wrapper
    func(*args, **kwargs)
  File "C:\Users\yucel\Insomniac\venv\lib\site-packages\insomniac\__init__.py", line 259, in job
    unfollow(device,
  File "<string>", line 10, in unfollow
  File "<string>", line 77, in _iterate_over_followings
  File "<string>", line 132, in _do_unfollow
  File "<string>", line 90, in save_crash
  File "<string>", line 72, in dump_hierarchy
  File "C:\Users\yucel\AppData\Local\Programs\Python\Python38\lib\encodings\cp1254.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0411' in position 11586: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 4, in <module>
    insomniac.run(activation_code)
  File "C:\Users\yucel\Insomniac\venv\lib\site-packages\insomniac\__init__.py", line 132, in run
    _job_unfollow(device,
  File "C:\Users\yucel\Insomniac\venv\lib\site-packages\insomniac\__init__.py", line 269, in _job_unfollow
    job()
  File "C:\Users\yucel\Insomniac\venv\lib\site-packages\insomniac\__init__.py", line 441, in wrapper
    save_crash(device)
  File "<string>", line 90, in save_crash
  File "<string>", line 72, in dump_hierarchy
  File "C:\Users\yucel\AppData\Local\Programs\Python\Python38\lib\encodings\cp1254.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0411' in position 11586: character maps to <undefined>
```

**Comment by alexal1** [comment]
Did it save crash .zip folder?

**Comment by yuceltoluyag** [comment]
> Did it save crash .zip folder?

![image](https://user-images.githubusercontent.com/16064131/97789962-a8dd6e00-1bd5-11eb-96f2-3ea02fe011ca.png)

there is no such file.
