### ISSUE TITLE
Cannot confirm unfollow -- Close instagram App

### ISSUE THREAD

**Issue by fabry46** [alexal1/Insomniac#170]
Hi guys 

i have the problem with the command 

**python start.py --unfollow-any 200-400**

[Crash-2020-11-02-10-30-21.zip](https://github.com/alexal1/Insomniac/files/5473986/Crash-2020-11-02-10-30-21.zip)

after a few unfollow the code it stopped

[error code.txt](https://github.com/alexal1/Insomniac/files/5473972/error.code.txt)

thanks so much :)

**Comment by fabry46** [comment]
Microsoft Windows [Versione 10.0.18363.1139]
(c) 2019 Microsoft Corporation. Tutti i diritti sono riservati.

C:\Users\Administrator>cd ins
Impossibile trovare il percorso specificato.

C:\Users\Administrator>cd Insomniac

C:\Users\Administrator\Insomniac>python start.py --unfollow-any 200-400
Insomniac v3.1.1

[11/02 10:24:05] Connected devices via adb: 1. That's ok.
[11/02 10:24:06] Instagram version: 165.1.0.29.119
[11/02 10:24:06] Using uiautomator v2
[W 201102 10:24:12 __init__:203] atx-agent has something wrong, auto recovering
[D 201102 10:24:12 __init__:287] device 7BQDU17119005076 is online
[I 201102 10:24:14 init:155] uiautomator2 version: 2.12.0
[11/02 10:24:17] Action: unfollow any 200-400

Hi! Since of v3.1.0 all core features in this project are free to use.
You may want to get more fine grained control over the bot via these features:
    - Filtering - skip unwanted accounts by various parameters
    - Removing mass followers - automate "cleaning" you account
    - Analytics tool - build presentation that shows your growth
    - Scrapping (next release) - will make interactions significantly safer and faster
Activate by supporting our small team: https://insomniac-bot.com/activate/

Activate the bot to use filter.json:
https://insomniac-bot.com/activate/

-------- START: 2020-11-02 10:24:17.979668 --------
[11/02 10:24:17] Open Instagram app
Warning: Activity not started, intent has been delivered to currently running top-most instance.
[11/02 10:24:18] Sleep for 1 second
[11/02 10:24:19] Press profile
[D 201102 10:24:20 __init__:600] kill process(ps): uiautomator
[D 201102 10:24:21 __init__:618] uiautomator-v2 is starting ... left: 40.0s
[D 201102 10:24:22 __init__:618] uiautomator-v2 is starting ... left: 39.0s
[D 201102 10:24:23 __init__:618] uiautomator-v2 is starting ... left: 38.0s
[D 201102 10:24:25 __init__:618] uiautomator-v2 is starting ... left: 36.9s
[D 201102 10:24:26 __init__:618] uiautomator-v2 is starting ... left: 35.9s
[D 201102 10:24:27 __init__:618] uiautomator-v2 is starting ... left: 34.9s
[D 201102 10:24:28 __init__:618] uiautomator-v2 is starting ... left: 33.9s
[D 201102 10:24:29 __init__:618] uiautomator-v2 is starting ... left: 32.8s
[I 201102 10:24:29 __init__:583] uiautomator back to normal
[11/02 10:24:30] Sleep for 4 seconds
[11/02 10:24:35] Hello, @viafauche_n35! You have 1458 followers and 7400 followings so far.

[11/02 10:24:35] Unfollow 353 any
[11/02 10:24:35] Open my followings
[11/02 10:24:35] Sort followings by date: from oldest to newest.
[11/02 10:24:41] Cannot find button to sort followings. Continue without sorting.
[11/02 10:24:41] Sleep for 1 second
[11/02 10:24:45] Iterate over visible followings
[11/02 10:24:45] Sleep for 3 seconds
[11/02 10:24:48] Unfollow @chiaraquaglio12
[11/02 10:24:52] Sleep for 2 seconds
[11/02 10:24:54] Dialog shown, confirm unfollowing.
[11/02 10:24:54] Sleep for 1 second
[11/02 10:25:01] Back to the followings list.
[11/02 10:25:02] Sleep for 4 seconds
[11/02 10:25:06] Need to scroll now
[11/02 10:25:07] Iterate over visible followings
[11/02 10:25:07] Sleep for 3 seconds
[11/02 10:25:11] Unfollow @carmineannarita
[11/02 10:25:13] Sleep for 3 seconds
[11/02 10:25:16] Dialog shown, confirm unfollowing.
[11/02 10:25:16] Sleep for 1 second
[11/02 10:25:24] Back to the followings list.
[11/02 10:25:24] Sleep for 1 second
[11/02 10:25:26] Skip @carmineannarita. Following status: UNFOLLOWED.
[11/02 10:25:26] Unfollow @pagano3914
[11/02 10:25:29] Sleep for 2 seconds
[11/02 10:25:31] Dialog shown, confirm unfollowing.
[11/02 10:25:31] Sleep for 1 second
[11/02 10:25:39] Back to the followings list.
[11/02 10:25:39] Sleep for 1 second
[11/02 10:25:40] Unfollow @trofeo_cuba
[11/02 10:25:45] Sleep for 3 seconds
[11/02 10:25:59] Back to the followings list.
[11/02 10:26:00] Sleep for 1 second
[11/02 10:26:01] Unfollow @ayari.hazem90
[11/02 10:26:04] Sleep for 4 seconds
[11/02 10:26:09] Dialog shown, confirm unfollowing.
[11/02 10:26:09] Sleep for 3 seconds
[11/02 10:26:18] Back to the followings list.
[11/02 10:26:18] Sleep for 2 seconds
[11/02 10:26:21] Unfollow @giorgino_83
[11/02 10:26:24] Sleep for 3 seconds
[11/02 10:26:38] Back to the followings list.
[11/02 10:26:38] Sleep for 3 seconds
[11/02 10:26:41] Unfollow @dronetopshoot
[11/02 10:26:44] Sleep for 1 second
[11/02 10:26:56] Back to the followings list.
[11/02 10:26:57] Sleep for 3 seconds
[11/02 10:27:00] Need to scroll now
[11/02 10:27:01] Iterate over visible followings
[11/02 10:27:01] Sleep for 2 seconds
[11/02 10:27:03] Unfollow @canzi
[11/02 10:27:07] Sleep for 4 seconds
[11/02 10:27:22] Back to the followings list.
[11/02 10:27:23] Sleep for 4 seconds
[11/02 10:27:27] Skip @canzi. Following status: UNFOLLOWED.
[11/02 10:27:27] Unfollow @lisottirosa
[11/02 10:27:30] Sleep for 1 second
[11/02 10:27:32] Dialog shown, confirm unfollowing.
[11/02 10:27:32] Sleep for 3 seconds
[11/02 10:27:41] Back to the followings list.
[11/02 10:27:41] Sleep for 1 second
[11/02 10:27:42] Unfollow @stefania.antonini.65
[11/02 10:27:45] Sleep for 2 seconds
[11/02 10:27:47] Dialog shown, confirm unfollowing.
[11/02 10:27:47] Sleep for 4 seconds
[11/02 10:27:57] Back to the followings list.
[11/02 10:27:58] Sleep for 4 seconds
[11/02 10:28:02] Unfollow @kekka_roberto
[11/02 10:28:05] Sleep for 2 seconds
[11/02 10:28:07] Dialog shown, confirm unfollowing.
[11/02 10:28:07] Sleep for 3 seconds
[11/02 10:28:16] Back to the followings list.
[11/02 10:28:16] Sleep for 1 second
[11/02 10:28:18] Unfollow @wanderlust1535
[11/02 10:28:21] Sleep for 4 seconds
[11/02 10:28:36] Back to the followings list.
[11/02 10:28:36] Sleep for 1 second
[11/02 10:28:38] Unfollow @alessiolado92
[11/02 10:28:41] Sleep for 3 seconds
[11/02 10:28:44] Dialog shown, confirm unfollowing.
[11/02 10:28:44] Sleep for 2 seconds
[11/02 10:28:52] Back to the followings list.
[11/02 10:28:52] Sleep for 1 second
[11/02 10:28:53] Need to scroll now
[11/02 10:28:54] Iterate over visible followings
[11/02 10:28:54] Sleep for 2 seconds
[11/02 10:28:57] Unfollow @basia.garwigarikos
[11/02 10:29:00] Sleep for 1 second
[11/02 10:29:12] Back to the followings list.
[11/02 10:29:12] Sleep for 4 seconds
[11/02 10:29:16] Skip @basia.garwigarikos. Following status: UNFOLLOWED.
[11/02 10:29:17] Unfollow @zoydzak
[11/02 10:29:20] Sleep for 4 seconds
[11/02 10:29:35] Back to the followings list.
[11/02 10:29:35] Sleep for 1 second
[11/02 10:29:36] Unfollow @juliet.witchcraft
[11/02 10:29:39] Sleep for 2 seconds
[11/02 10:29:52] Back to the followings list.
[11/02 10:29:52] Sleep for 1 second
[11/02 10:29:54] Unfollow @giacomoadragna1980
[11/02 10:29:57] Sleep for 2 seconds
[11/02 10:30:10] Back to the followings list.
[11/02 10:30:10] Sleep for 3 seconds
[11/02 10:30:13] Unfollow @ianisalexandru04
[11/02 10:30:21] Cannot confirm unfollow.
[11/02 10:30:22] Crash saved as "crashes/Crash-2020-11-02-10-30-21.zip".
[11/02 10:30:22] Please attach this file if you gonna report the crash at
[11/02 10:30:22] https://github.com/alexal1/Insomniac/issues

[11/02 10:30:22] Sleep for 4 seconds
[11/02 10:30:26] Unfollow @redamoc
[11/02 10:30:34] Cannot confirm unfollow.
[11/02 10:30:34] Directory Crash-2020-11-02-10-30-34 already exists.
[11/02 10:30:34] Close Instagram app


TOTAL
Completed sessions: 0
Total duration: 0:06:17.744225
Total interactions: 0
Successful interactions: 0
Total followed : 0
Total likes: 0
Total unfollowed: 17
Removed mass followers: none
Traceback (most recent call last):
  File "start.py", line 4, in <module>
    insomniac.run(activation_code)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\insomniac\__init__.py", line 132, in run
    _job_unfollow(device,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\insomniac\__init__.py", line 269, in _job_unfollow
    job()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\insomniac\__init__.py", line 445, in wrapper
    raise e
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\insomniac\__init__.py", line 418, in wrapper
    func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\insomniac\__init__.py", line 259, in job
    unfollow(device,
  File "<string>", line 10, in unfollow
  File "<string>", line 77, in _iterate_over_followings
  File "<string>", line 132, in _do_unfollow
  File "<string>", line 90, in save_crash
  File "<string>", line 72, in dump_hierarchy
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0117' in position 24145: character maps to <undefined>

C:\Users\Administrator\Insomniac>

**Comment by fabry46** [comment]
.... hi guyssss ... can anyone help me?

**Comment by GitNees** [comment]
Try to launch your command with this added paramater. This enables UTF8, let me know if that fixed it. As i tried it for now and didnt encounter issues on crashing on strange characters.

python -Xutf8 start.py --unfollow-any 200-400

Let me know how that goes

**Comment by fabry46** [comment]
> Try to launch your command with this added paramater. This enables UTF8, let me know if that fixed it. As i tried it for now and didnt encounter issues on crashing on strange characters.
> 
> python -Xutf8 start.py --unfollow-any 200-400
> 
> Let me know how that goes

hey man , your help was brilliant !! works perfectly now .. thank you very much you have been of great help
