### ISSUE TITLE
crashes liking #hashtag

### ISSUE THREAD

**Issue by soulpawa** [alexal1/Insomniac#178]
I found 2 problems / scenarios one keeps liking on the same post:

11/06 10:05:12] Iterate over visible likers.
[11/06 10:05:12] @akihito_baron: already interacted. Skip.
[11/06 10:05:13] @dblackbarbeariasp: already interacted. Skip.
[11/06 10:05:13] Iterated exactly the same likers twice, finish.
[11/06 10:05:13] Back to #shave
[11/06 10:05:24] Traceback (most recent call last):
  File "<string>", line 174, in scroll
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/_selector.py", line 575, in __call__
    max_swipes, steps)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 436, in __call__
    http_timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 442, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 514, in _jsonrpc_call
    raise err

another problem is when the post has not likes from nobody 

11/06 10:12:39] Handle #shave
[11/06 10:12:39] Interactions count: 25
[11/06 10:12:39] Press search
[11/06 10:12:42] Open hashtag #shave
[11/06 10:12:45] Sleep for 4 seconds
[11/06 10:12:49] Switching to Recent tab
[11/06 10:12:53] Sleep for 3 seconds
[11/06 10:12:56] Opening the first post
[11/06 10:12:57] Sleep for 1 second
[11/06 10:12:59] No likes, let's scroll down.
[11/06 10:13:10] Traceback (most recent call last):
  File "<string>", line 174, in scroll
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/_selector.py", line 575, in __call__
    max_swipes, steps)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 436, in __call__
    http_timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 442, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 514, in _jsonrpc_call
    raise err
uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=androidx.recyclerview.widget.RecyclerView, RESOURCE_ID=android:id/list], method: scrollToEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/__init__.py", line 418, in wrapper
    func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/__init__.py", line 227, in job
    on_interaction)
  File "<string>", line 48, in handle_hashtag
  File "<string>", line 176, in scroll
insomniac.device_facade.DeviceFacade.JsonRpcError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=androidx.recyclerview.widget.RecyclerView, RESOURCE_ID=android:id/list], method: scrollToEnd

WARNING:root:HTTPConnectionPool(host='localhost', port=59047): Read timed out. (read timeout=10), retrying in 0.5 seconds...

no crash.zip as it's empty on the folder

**Comment by rajASSop** [comment]
can you give me a link to your repo so I will run and look forward to your issue.....
I tried to find that but I didn't get it

**Comment by rajASSop** [comment]
> I found 2 problems / scenarios one keeps liking on the same post:
> 
> 11/06 10:05:12] Iterate over visible likers.
> [11/06 10:05:12] @akihito_baron: already interacted. Skip.
> [11/06 10:05:13] @dblackbarbeariasp: already interacted. Skip.
> [11/06 10:05:13] Iterated exactly the same likers twice, finish.
> [11/06 10:05:13] Back to #shave
> [11/06 10:05:24] Traceback (most recent call last):
> File "", line 174, in scroll
> File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/_selector.py", line 575, in **call**
> max_swipes, steps)
> File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/**init**.py", line 436, in **call**
> http_timeout)
> File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/**init**.py", line 442, in _jsonrpc_retry_call
> return self._jsonrpc_call(*args, **kwargs)
> File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/**init**.py", line 514, in _jsonrpc_call
> raise err
> 
> another problem is when the post has not likes from nobody
> 
> 11/06 10:12:39] Handle #shave
> [11/06 10:12:39] Interactions count: 25
> [11/06 10:12:39] Press search
> [11/06 10:12:42] Open hashtag #shave
> [11/06 10:12:45] Sleep for 4 seconds
> [11/06 10:12:49] Switching to Recent tab
> [11/06 10:12:53] Sleep for 3 seconds
> [11/06 10:12:56] Opening the first post
> [11/06 10:12:57] Sleep for 1 second
> [11/06 10:12:59] No likes, let's scroll down.
> [11/06 10:13:10] Traceback (most recent call last):
> File "", line 174, in scroll
> File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/_selector.py", line 575, in **call**
> max_swipes, steps)
> File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/**init**.py", line 436, in **call**
> http_timeout)
> File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/**init**.py", line 442, in _jsonrpc_retry_call
> return self._jsonrpc_call(*args, **kwargs)
> File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/**init**.py", line 514, in _jsonrpc_call
> raise err
> uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=androidx.recyclerview.widget.RecyclerView, RESOURCE_ID=android:id/list], method: scrollToEnd
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/home/pi/.local/lib/python3.7/site-packages/insomniac/**init**.py", line 418, in wrapper
> func(*args, **kwargs)
> File "/home/pi/.local/lib/python3.7/site-packages/insomniac/**init**.py", line 227, in job
> on_interaction)
> File "", line 48, in handle_hashtag
> File "", line 176, in scroll
> insomniac.device_facade.DeviceFacade.JsonRpcError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=androidx.recyclerview.widget.RecyclerView, RESOURCE_ID=android:id/list], method: scrollToEnd
> 
> WARNING:root:HTTPConnectionPool(host='localhost', port=59047): Read timed out. (read timeout=10), retrying in 0.5 seconds...
> 
> no crash.zip as it's empty on the folder

can you give me a link to your repo so I will run and look forward to your issue.....
I tried to find that but I didn't get it

**Comment by alexal1** [comment]
We will publish all code in 1-3 days, we're making a clean-up right now.

**Comment by Fadude** [comment]
Fixed on 3.5.0
