### ISSUE TITLE
After get the last update - AttributeError: module 'speedtest' has no attribute 'SpeedtestException'

### ISSUE THREAD

**Issue by marciomvm** [alexal1/Insomniac#201]
Traceback (most recent call last):
  File "start.py", line 4, in <module>
    insomniac.run(activation_code)
  File "C:\Users\Marcio\Downloads\Insomniac\Insomniac\insomniac\__init__.py", line 20, in run
    insomniac_session.run()
  File "C:\Users\Marcio\Downloads\Insomniac\Insomniac\insomniac\session.py", line 135, in run
    sleeper.update_random_sleep_range()
  File "C:\Users\Marcio\Downloads\Insomniac\Insomniac\insomniac\sleeper.py", line 36, in update_random_sleep_range
    speed = _get_internet_speed()
  File "C:\Users\Marcio\Downloads\Insomniac\Insomniac\insomniac\sleeper.py", line 67, in _get_internet_speed
    except speedtest.SpeedtestException:
AttributeError: module 'speedtest' has no attribute 'SpeedtestException'

**Comment by zubus** [comment]
Hey! Try [GramAddict](https://github.com/GramAddict/bot) better fork of insomniac, full open source and free ;)
Ps and without bugs :P

**Comment by Fadude** [comment]
Fixed on 3.4.1. Closing.
