### ISSUE TITLE
Bot crashes every 30 min

### ISSUE THREAD

**Issue by Sudge32** [alexal1/Insomniac#202]
`[12/01 11:31:52] Traceback (most recent call last):
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\device_facade.py", line 205, in scroll
    self.viewV2.scroll.toEnd(max_swipes=1)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\_selector.py", line 574, in __call__
    return jsonrpc.scrollToEnd(selector, self.vertical,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 435, in __call__
    return self.server._jsonrpc_retry_call(self.method, params,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 442, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 514, in _jsonrpc_call
    raise err
uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=androidx.recyclerview.widget.RecyclerView, RESOURCE_ID=android:id/list], method: scrollToEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\safely_runner.py", line 18, in wrapper
    func(*args, **kwargs)
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\actions_runners.py", line 212, in job
    handle_hashtag(device_wrapper.get(),
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\action_handle_hashtag.py", line 179, in handle_hashtag
    extract_hashtag_profiles_and_interact(device,
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\action_handle_hashtag.py", line 243, in extract_hashtag_profiles_and_interact
    posts_list_view.scroll(DeviceFacade.Direction.BOTTOM)
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\device_facade.py", line 207, in scroll
    raise DeviceFacade.JsonRpcError(e)
insomniac.device_facade.DeviceFacade.JsonRpcError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=androidx.recyclerview.widget.RecyclerView, RESOURCE_ID=android:id/list], method: scrollToEnd

Caught an exception:
[WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'crashes\\Crash-2020-12-01-11-31-52'

Traceback (most recent call last):
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\device_facade.py", line 205, in scroll
    self.viewV2.scroll.toEnd(max_swipes=1)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\_selector.py", line 574, in __call__
    return jsonrpc.scrollToEnd(selector, self.vertical,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 435, in __call__
    return self.server._jsonrpc_retry_call(self.method, params,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 442, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 514, in _jsonrpc_call
    raise err
uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=androidx.recyclerview.widget.RecyclerView, RESOURCE_ID=android:id/list], method: scrollToEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\safely_runner.py", line 18, in wrapper
    func(*args, **kwargs)
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\actions_runners.py", line 212, in job
    handle_hashtag(device_wrapper.get(),
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\action_handle_hashtag.py", line 179, in handle_hashtag
    extract_hashtag_profiles_and_interact(device,
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\action_handle_hashtag.py", line 243, in extract_hashtag_profiles_and_interact
    posts_list_view.scroll(DeviceFacade.Direction.BOTTOM)
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\device_facade.py", line 207, in scroll
    raise DeviceFacade.JsonRpcError(e)
insomniac.device_facade.DeviceFacade.JsonRpcError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=androidx.recyclerview.widget.RecyclerView, RESOURCE_ID=android:id/list], method: scrollToEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\session.py", line 152, in run
    action_runner.run(device_wrapper,
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\actions_runners.py", line 229, in run
    job()
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\safely_runner.py", line 29, in wrapper
    save_crash(device_wrapper.get(), ex)
  File "C:\Users\user\Dropbox\Insomniac-master\insomniac\utils.py", line 109, in save_crash
    shutil.rmtree(os.path.join("crashes", directory_name))
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 617, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'crashes\\Crash-2020-12-01-11-31-52'
`

**Comment by zubus** [comment]
Hey! Try [GramAddict](https://github.com/GramAddict/bot) better fork of insomniac, full open source and free ;)
Ps and without bugs :P

**Comment by Fadude** [comment]
Can you share crash-zip please?
