### ISSUE TITLE
IGTV Bypass - Error message

### ISSUE THREAD

**Issue by gvmturl** [alexal1/Insomniac#21]
```
[91mTraceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator\__init__.py", line 438, in wrapper
    return _method_obj(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator\__init__.py", line 135, in __call__
    "%s: %s" % (jsonresult["error"]["data"]["exceptionTypeName"], jsonresult["error"]["message"])
uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.FrameLayout, RESOURCE_ID=com.instagram.android:id/action_bar_container]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insomniac.py", line 89, in _job_handle_bloggers
    handle_blogger(device, blogger, likes_count, storage, _on_like, on_interaction)
  File "C:\Users\User\Downloads\Insomniac2\action_handle_blogger.py", line 18, in handle_blogger
    _iterate_over_followers(device, interaction, storage, on_interaction)
  File "C:\Users\User\Downloads\Insomniac2\action_handle_blogger.py", line 69, in _iterate_over_followers
    interaction_succeed = interaction(device)
  File "C:\Users\User\Downloads\Insomniac2\action_handle_blogger.py", line 109, in _interact_with_user
    if not _open_photo_and_like(device, row, column, on_like):
  File "C:\Users\User\Downloads\Insomniac2\action_handle_blogger.py", line 143, in _open_photo_and_like
    action_bar_bottom = action_bar.bounds['bottom']
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator\__init__.py", line 934, in __getattr__
    info = self.info
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator\__init__.py", line 945, in info
    return self.jsonrpc.objInfo(self.selector)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator\__init__.py", line 458, in wrapper
    return _method_obj(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator\__init__.py", line 135, in __call__
    "%s: %s" % (jsonresult["error"]["data"]["exceptionTypeName"], jsonresult["error"]["message"])
uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.FrameLayout, RESOURCE_ID=com.instagram.android:id/action_bar_container]
[0m
Try again for @codes.learning from the beginning
```
Think that you found a way to handle IGTV BUG but i still getting this error message on this solution. Can you also handle this message?

Thank you!

**Comment by gvmturl** [comment]
```
[93mLess than 6 photos / account is private. Skip user.[0m
Back to followers list
[91mTraceback (most recent call last):
  File "insomniac.py", line 89, in _job_handle_bloggers
    handle_blogger(device, blogger, likes_count, storage, _on_like, on_interaction)
  File "C:\Users\User\Downloads\Insomniac2\action_handle_blogger.py", line 18, in handle_blogger
    _iterate_over_followers(device, interaction, storage, on_interaction)
  File "C:\Users\User\Downloads\Insomniac2\action_handle_blogger.py", line 51, in _iterate_over_followers
    className='android.widget.LinearLayout'):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator\__init__.py", line 1222, in next
    return obj[self.index]
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator\__init__.py", line 1203, in __getitem__
    raise IndexError()
IndexError
[0m
Try again for @python.learning from the beginning
```

Also getting this error message didn't see when ..

**Comment by alexal1** [comment]
> Think that you found a way to handle IGTV BUG

No, unfortunately, I don't know why is IGTV sometimes being opened. I've tried to reproduce this bug many times on a profile with IGTV's, but didn't succeed. I've made some kind of "autorepair" instead: whenever script fails with some know error, like one you've posted, it starts current blogger from the beginning.

> What must i do to see that �[ ? Are you coloring text on terminal right?

Yes, seems that coloring on Mac and Windows terminals works different. Do you know the proper way to do the coloring in Python for Windows?

**Comment by gvmturl** [comment]
> > Think that you found a way to handle IGTV BUG
> 
> No, unfortunately, I don't know why is IGTV sometimes being opened. I've tried to reproduce this bug many times on a profile with IGTVs, but didn't succeed. I've made some kind of "autorepair" instead: whenever script fails with some known error, like one you've posted, it starts current blogger from the beginning.
> 
> > What must i do to see that �[ ? Are you coloring text on terminal right?
> 
> Yes, seems that coloring on Mac and Windows terminals works different. Do you know the proper way to do the coloring in Python for Windows?

```
import os
os.system('color 4')
```

try using `color --help` on cmd to take collors numbers.

**Comment by alexal1** [comment]
Done, please check on your machine.

**Comment by gvmturl** [comment]
Thanks, i will mark it as closed to concentrate discussion about error message on #19.
