### ISSUE TITLE
Regular error, no idea why

### ISSUE THREAD

**Issue by albir44** [alexal1/Insomniac#264]
No idea why it's happening, once a day minimum. 

 File "/home/pi/.local/lib/python3.7/site-packages/insomniac/device_facade.py", line 520, in get_bounds
    return self.viewV2.info['bounds']
  File "<decorator-gen-4>", line 2, in info
  File "/home/pi/.local/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/home/pi/.local/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/_selector.py", line 130, in info
    return self.jsonrpc.objInfo(self.selector)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 435, in __call__
    http_timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 441, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 513, in _jsonrpc_call
    raise err
uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=android.widget.FrameLayout, RESOURCE_ID_REGEX=com.instagram.android:id/zoomable_view_container|com.instagram.android:id/carousel_image], method: objInfo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/safely_runner.py", line 14, in wrapper
    func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/action_runners/interact/__init__.py", line 160, in job
    self.action_status)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/action_runners/interact/action_handle_blogger.py", line 246, in handle_blogger
    followers_following_list_view.iterate_over_followers(is_myself, interact_with_follower, pre_conditions)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/views.py", line 1160, in iterate_over_followers
    to_continue = iteration_callback(username, user_name_view)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/action_runners/interact/action_handle_blogger.py", line 206, in interact_with_follower
    is_liked, is_followed, is_watch, is_commented = interaction(username=follower_name, interaction_strategy=interaction_strategy)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/actions_impl.py", line 320, in interact_with_user
    do_like_actions()
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/actions_impl.py", line 298, in do_like_actions
    interaction_strategy.comments_list, my_username, on_comment):
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/actions_impl.py", line 371, in _open_photo_and_like_and_comment
    post_view.double_click()
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/device_facade.py", line 439, in double_click
    self._double_click_v2(padding)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/device_facade.py", line 607, in _double_click_v2
    visible_bounds = self.get_bounds()
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/device_facade.py", line 522, in get_bounds
    raise DeviceFacade.JsonRpcError(e)
insomniac.device_facade.DeviceFacade.JsonRpcError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=android.widget.FrameLayout, RESOURCE_ID_REGEX=com.instagram.android:id/zoomable_view_container|com.instagram.android:id/carousel_image], method: objInfo

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/device_facade.py", line 520, in get_bounds
    return self.viewV2.info['bounds']
  File "<decorator-gen-4>", line 2, in info
  File "/home/pi/.local/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/home/pi/.local/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/_selector.py", line 130, in info
    return self.jsonrpc.objInfo(self.selector)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 435, in __call__
    http_timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 441, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 513, in _jsonrpc_call
    raise err
uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=android.widget.FrameLayout, RESOURCE_ID_REGEX=com.instagram.android:id/zoomable_view_container|com.instagram.android:id/carousel_image], method: objInfo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/safely_runner.py", line 14, in wrapper
    func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/action_runners/interact/__init__.py", line 160, in job
    self.action_status)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/action_runners/interact/action_handle_blogger.py", line 246, in handle_blogger
    followers_following_list_view.iterate_over_followers(is_myself, interact_with_follower, pre_conditions)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/views.py", line 1160, in iterate_over_followers
    to_continue = iteration_callback(username, user_name_view)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/action_runners/interact/action_handle_blogger.py", line 206, in interact_with_follower
    is_liked, is_followed, is_watch, is_commented = interaction(username=follower_name, interaction_strategy=interaction_strategy)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/actions_impl.py", line 320, in interact_with_user
    do_like_actions()
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/actions_impl.py", line 298, in do_like_actions
    interaction_strategy.comments_list, my_username, on_comment):
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/actions_impl.py", line 371, in _open_photo_and_like_and_comment
    post_view.double_click()
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/device_facade.py", line 439, in double_click
    self._double_click_v2(padding)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/device_facade.py", line 607, in _double_click_v2
    visible_bounds = self.get_bounds()
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/device_facade.py", line 522, in get_bounds
    raise DeviceFacade.JsonRpcError(e)
insomniac.device_facade.DeviceFacade.JsonRpcError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=android.widget.FrameLayout, RESOURCE_ID_REGEX=com.instagram.android:id/zoomable_view_container|com.instagram.android:id/carousel_image], method: objInfo

**Comment by mdlaizure** [comment]
I'm getting the same error at least once a session

**Comment by Fadude** [comment]
Please update to 3.6.10, should be fixed

**Comment by mdlaizure** [comment]
I have it running now so far so good.

**Comment by alexal1** [comment]
Fixed in `v3.7.0`
