### ISSUE TITLE
JSON Decoder Problem with Interact --config-file

### ISSUE THREAD

**Issue by fp231** [alexal1/Insomniac#269]
Hey, am still loving this project and i run multiple devices with great fun. 

But i encountered an issue with the the run config-file option. IUf i use interact i have no problem at all. Just when i try to use the config file .json i get the following erreo:

[02/15 19:02:34] Your activation code is confirmed, welcome!
Traceback (most recent call last):
  File "start.py", line 4, in <module>
    insomniac.run(activation_code)
  File "/home/pi/Desktop/insomniac/insomniac/__init__.py", line 27, in run
    insomniac_session.run()
  File "<string>", line 127, in run
  File "/home/pi/Desktop/insomniac/insomniac/session.py", line 136, in parse_args
    ok, args = parse_arguments(self.get_session_args())
  File "/home/pi/Desktop/insomniac/insomniac/params.py", line 42, in parse_arguments
    refresh_args_by_conf_file(args)
  File "/home/pi/Desktop/insomniac/insomniac/params.py", line 68, in refresh_args_by_conf_file
    params = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 87 column 5 (char 3603)

Does anybody have an idea what i am missing? Thanks

**Comment by Fadude** [comment]
Seems like you have a json format issue on your config file (line 87, probably some , is missing or something like that..).
Try to validate your json stracture

**Comment by fp231** [comment]
And it the .json was corrupted in line 87. Thank for hinting to my stupidness so kindly. I love this community and this great thing you call insomniac. Thanks.
