### ISSUE TITLE
remove_mass_followers error

### ISSUE THREAD

**Issue by cecimascaras** [alexal1/Insomniac#277]
Caught an exception:
'NoneType' object has no attribute 'exists'
[02/24 12:58:10] Traceback (most recent call last):
  File "<string>", line 182, in run
  File "<string>", line 215, in run
  File "D:\Insomniac-master3\insomniac\safely_runner.py", line 14, in wrapper
    func(*args, **kwargs)
  File "<string>", line 205, in job
  File "<string>", line 76, in remove_mass_followers
  File "D:\Insomniac-master3\insomniac\actions_impl.py", line 129, in iterate_over_followers
    to_continue = iteration_callback(username, user_name_view)
  File "<string>", line 70, in iteration_callback
  File "<string>", line 11, in remove_mass_follower
  File "D:\Insomniac-master3\insomniac\device_facade.py", line 516, in exists
    return self.viewV2.exists(UI_TIMEOUT_SHORT if quick else UI_TIMEOUT_LONG)
AttributeError: 'NoneType' object has no attribute 'exists'

[XG3-REMOVE-mass-followers.zip](https://github.com/alexal1/Insomniac/files/6037268/XG3-REMOVE-mass-followers.zip) JSON

[Crash-2021-02-24-12-58-10.zip](https://github.com/alexal1/Insomniac/files/6037249/Crash-2021-02-24-12-58-10.zip)

**Comment by Haterz-D** [comment]
I have the same problem, did you manage to fix it?
