### ISSUE TITLE
Error on startup. can you help me?

### ISSUE THREAD

**Issue by ni6htfall** [alexal1/Insomniac#280]
I just installed everything, insomniac gets to open IG but crashes afterwards...
I downgraded to IG version 132.0.0.8.134, thinking maybe its not yet compatible with the latest one but same crash.
this is the crashlog, can you help me?

"
Using insomniac session-manager without extra-features
[03/04 19:32:57] Checking your Internet speed to adjust the script speed, please wait for a minute...
[03/04 19:32:57] (use --no-speed-check to skip this check)
[03/04 19:33:19] Download speed 15.49 Mbit/s, upload speed 19.87 Mbit/s
[03/04 19:33:19] Sleep range will be from 1.49 to 3.98 seconds
Looking for ADB devices...
Connected devices via adb: 1. That's ok.
[03/04 19:33:20] Using uiautomator v2
[03/04 19:33:20] Instagram version: not found
[03/04 19:33:20] Sleep time (min) before repeat: 56
[03/04 19:33:20] Running Insomniac with the "interact" action.
[03/04 19:33:20] You are using a deprecated limit. The limit new name is called 'successful_interactions_limit_per_source'. Using interactions_count this time. Please switch to that name on next runs.
[03/04 19:33:20] Interactions count: 29
[03/04 19:33:20] Successful interactions limit per source: 70
[03/04 19:33:20] Interactions limit per source: 140
[03/04 19:33:20] Total likes limit: 1000
[03/04 19:33:20] Total comments limit: 50

-------- START: 2021-03-04 19:33:20.907237 --------
[03/04 19:33:21] Close Instagram app
[03/04 19:33:21] Sleep for 2.53 seconds
[03/04 19:33:23] Open Instagram app
[03/04 19:33:24] Sleep for 2.18 seconds
[03/04 19:33:26] Closing keyboard...
[03/04 19:33:26] The device keyboard is already closed.
[03/04 19:33:33] Didn't find tab PROFILE in the tab bar... Maybe English language is not set!?
[03/04 19:33:33] Exception: 
[03/04 19:33:34] Crash saved as "crashes/Crash-2021-03-04-19-33-33.zip".
[03/04 19:33:34] Please attach this file if you gonna report the crash at
[03/04 19:33:34] https://github.com/alexal1/Insomniac/issues

[03/04 19:33:34] Switching to English locale
[03/04 19:33:34] Press profile
[03/04 19:33:34] Closing keyboard...
[03/04 19:33:34] The device keyboard is already closed.

Caught an exception:
-32002 Client error: <> data: Selector [childOrSibling=['child'], childOrSiblingSelector=[{'mask': 8388608, 'childOrSibling': [], 'childOrSiblingSelector': [], 'index': 4}], resourceId='com.instagram.android:id/tab_bar', className='android.widget.LinearLayout'], method: None
[03/04 19:33:40] Traceback (most recent call last):
  File "C:\Users\Nightfall\insomniac\insomniac\action_get_my_profile_info.py", line 9, in get_my_profile_info
    profile_view = TabBarView(device).navigate_to_profile()
  File "C:\Users\Nightfall\insomniac\insomniac\views.py", line 91, in navigate_to_profile
    self._navigate_to(TabBarTabs.PROFILE)
  File "C:\Users\Nightfall\insomniac\insomniac\views.py", line 140, in _navigate_to
    raise LanguageNotEnglishException()
insomniac.views.LanguageNotEnglishException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nightfall\insomniac\insomniac\device_facade.py", line 437, in click
    self.viewV2.click(UI_TIMEOUT_LONG, offset=(x_offset, y_offset))
  File "C:\Users\Nightfall\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\_selector.py", line 150, in click
    self.must_wait(timeout=timeout)
  File "C:\Users\Nightfall\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\_selector.py", line 345, in must_wait
    raise UiObjectNotFoundError({'code': -32002, 'data': str(self.selector), 'method': 'wait'})
uiautomator2.exceptions.UiObjectNotFoundError: -32002 Client error: <> data: Selector [childOrSibling=['child'], childOrSiblingSelector=[{'mask': 8388608, 'childOrSibling': [], 'childOrSiblingSelector': [], 'index': 4}], resourceId='com.instagram.android:id/tab_bar', className='android.widget.LinearLayout'], method: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nightfall\insomniac\insomniac\session.py", line 231, in run
    self.start_session(args, device_wrapper, app_version, save_profile_info=True)
  File "C:\Users\Nightfall\insomniac\insomniac\session.py", line 168, in start_session
    self.session_state.my_following_count = get_my_profile_info(device_wrapper.get(), self.username)
  File "C:\Users\Nightfall\insomniac\insomniac\action_get_my_profile_info.py", line 30, in get_my_profile_info
    switch_to_english(device)
  File "C:\Users\Nightfall\insomniac\insomniac\navigation.py", line 47, in switch_to_english
    navigate(device, Tabs.PROFILE)
  File "C:\Users\Nightfall\insomniac\insomniac\navigation.py", line 25, in navigate
    button.click()
  File "C:\Users\Nightfall\insomniac\insomniac\device_facade.py", line 439, in click
    raise DeviceFacade.JsonRpcError(e)
insomniac.device_facade.DeviceFacade.JsonRpcError: -32002 Client error: <> data: Selector [childOrSibling=['child'], childOrSiblingSelector=[{'mask': 8388608, 'childOrSibling': [], 'childOrSiblingSelector': [], 'index': 4}], resourceId='com.instagram.android:id/tab_bar', className='android.widget.LinearLayout'], method: None

Traceback (most recent call last):
  File "C:\Users\Nightfall\insomniac\insomniac\action_get_my_profile_info.py", line 9, in get_my_profile_info
    profile_view = TabBarView(device).navigate_to_profile()
  File "C:\Users\Nightfall\insomniac\insomniac\views.py", line 91, in navigate_to_profile
    self._navigate_to(TabBarTabs.PROFILE)
  File "C:\Users\Nightfall\insomniac\insomniac\views.py", line 140, in _navigate_to
    raise LanguageNotEnglishException()
insomniac.views.LanguageNotEnglishException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nightfall\insomniac\insomniac\device_facade.py", line 437, in click
    self.viewV2.click(UI_TIMEOUT_LONG, offset=(x_offset, y_offset))
  File "C:\Users\Nightfall\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\_selector.py", line 150, in click
    self.must_wait(timeout=timeout)
  File "C:\Users\Nightfall\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\_selector.py", line 345, in must_wait
    raise UiObjectNotFoundError({'code': -32002, 'data': str(self.selector), 'method': 'wait'})
uiautomator2.exceptions.UiObjectNotFoundError: -32002 Client error: <> data: Selector [childOrSibling=['child'], childOrSiblingSelector=[{'mask': 8388608, 'childOrSibling': [], 'childOrSiblingSelector': [], 'index': 4}], resourceId='com.instagram.android:id/tab_bar', className='android.widget.LinearLayout'], method: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nightfall\insomniac\insomniac\session.py", line 231, in run
    self.start_session(args, device_wrapper, app_version, save_profile_info=True)
  File "C:\Users\Nightfall\insomniac\insomniac\session.py", line 168, in start_session
    self.session_state.my_following_count = get_my_profile_info(device_wrapper.get(), self.username)
  File "C:\Users\Nightfall\insomniac\insomniac\action_get_my_profile_info.py", line 30, in get_my_profile_info
    switch_to_english(device)
  File "C:\Users\Nightfall\insomniac\insomniac\navigation.py", line 47, in switch_to_english
    navigate(device, Tabs.PROFILE)
  File "C:\Users\Nightfall\insomniac\insomniac\navigation.py", line 25, in navigate
    button.click()
  File "C:\Users\Nightfall\insomniac\insomniac\device_facade.py", line 439, in click
    raise DeviceFacade.JsonRpcError(e)
insomniac.device_facade.DeviceFacade.JsonRpcError: -32002 Client error: <> data: Selector [childOrSibling=['child'], childOrSiblingSelector=[{'mask': 8388608, 'childOrSibling': [], 'childOrSiblingSelector': [], 'index': 4}], resourceId='com.instagram.android:id/tab_bar', className='android.widget.LinearLayout'], method: None

**Comment by alexal1** [comment]
@ni6htfall is there English language set in your Instagram?

**Comment by ni6htfall** [comment]
yes!

**Comment by ni6htfall** [comment]
![screenshot 1](https://user-images.githubusercontent.com/80064802/110029926-5d7ace00-7d35-11eb-9d8c-9d0e1ce2121e.jpg)
is it normal that the screen is seen like this? this comes from the crash log, in my phone I can see it fine.

**Comment by ni6htfall** [comment]
downgraded to python 3.8.6 still the same crash

**Comment by soulpawa** [comment]
same problem here
