### ISSUE TITLE
Interact targets: json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes

### ISSUE THREAD

**Issue by scheherazade1** [alexal1/Insomniac#284]
Hey Guys,

I used the scraping function for my main account. When I try to interact with the targets, I receive the error below. Unfortunately, I am a total newbie. I would appreciate if someone could help me. I also tried to find the fault in line 15 column 1. But I don't know to which file it is related. All I checked were fine.

Thanks for your help!

Traceback (most recent call last):
  File "C:\Users\Documents\Insomniac-master\start.py", line 4, in <module>
    insomniac.run(activation_code)
  File "C:\Users\Documents\Insomniac-master\insomniac\__init__.py", line 30, in run
    insomniac_session.run()
  File "<string>", line 170, in run
  File "<string>", line 58, in set_filters
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 15 column 1 (char 425)

**Comment by alexal1** [comment]
Hey @scheherazade1!
Looks like your filters.json (or your config file) is not properly formatted. You can attach them here if you want us to help you
