### ISSUE TITLE
removing mass follower error

### ISSUE THREAD

**Issue by Haterz-D** [alexal1/Insomniac#286]
this error is generated when the bot tries to remove a follower:

[03/13 22:04:33] Open @sergeykroitoruofficial
[03/13 22:04:34] Sleep for 1.12 seconds
[03/13 22:04:37] @sergeykroitoruofficial has 3962 followings
[03/13 22:04:37] @sergeykroitoruofficial is mass follower, remove.

Caught an exception:
'NoneType' object has no attribute 'exists'
[03/13 22:04:37] Traceback (most recent call last):
  File "<string>", line 182, in run
  File "<string>", line 215, in run
  File "C:\Users\dispr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\safely_runner.py", line 14, in wrapper
    func(*args, **kwargs)
  File "<string>", line 205, in job
  File "<string>", line 76, in remove_mass_followers
  File "C:\Users\dispr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\actions_impl.py", line 129, in iterate_over_followers
    to_continue = iteration_callback(username, user_name_view)
  File "<string>", line 70, in iteration_callback
  File "<string>", line 11, in remove_mass_follower
  File "C:\Users\dispr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\device_facade.py", line 516, in exists
    return self.viewV2.exists(UI_TIMEOUT_SHORT if quick else UI_TIMEOUT_LONG)
AttributeError: 'NoneType' object has no attribute 'exists'

**Comment by Haterz-D** [comment]
I tried to use different python 3.x versions, real Android device connected via USB and Android emulator and still get the same error every time the bot find the 1st follower to remove.

**Comment by alexal1** [comment]
Will be fixed in `v3.7.1`
