### ISSUE TITLE
Insomniac doesn't start

### ISSUE THREAD

**Issue by yondermann** [alexal1/Insomniac#311]
Hi,
Yesterday everything was working fine. I shut down everything as I always do and today when I wanted to start the program it didn't work. I upgraded to 3.7.2 but nothing changed.
This is what I get when running this script:
py start.py --interact @buzzfeedtasty-followers --successful-interactions-limit-per-source 30-70 --likes-count 1-2 --follow-percentage 80 --repeat 160-220

Using insomniac session-manager without extra-features
[04/08 09:54:02] Checking your Internet speed to adjust the script speed, please wait for a minute...
[04/08 09:54:02] (use --no-speed-check to skip this check)
Traceback (most recent call last):
  File "C:\Users\BlackMantis\Utiles\insomniac\start.py", line 4, in <module>
    insomniac.run(activation_code)
  File "C:\Users\BlackMantis\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\__init__.py", line 30, in run
    insomniac_session.run()
  File "C:\Users\BlackMantis\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\session.py", line 218, in run
    sleeper.update_random_sleep_range()
  File "C:\Users\BlackMantis\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\sleeper.py", line 33, in update_random_sleep_range
    speed = _get_internet_speed()
  File "C:\Users\BlackMantis\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\sleeper.py", line 61, in _get_internet_speed
    s = speedtest.Speedtest()
  File "C:\Users\BlackMantis\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\tools\speedtest.py", line 964, in __init__
    self.get_config()
  File "C:\Users\BlackMantis\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\tools\speedtest.py", line 1046, in get_config
    ignore_servers = list(
ValueError: invalid literal for int() with base 10: ''

**Comment by Fadude** [comment]
We are investigating the issue, in the meantime, run with `--no-speed-check` parameter

**Comment by alexal1** [comment]
Will be fixed in next release
