### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 40 column 16 (char 1398)

### ISSUE THREAD

**Issue by marco1m** [alexal1/Insomniac#317]
I just stopped working. Now it gives me the following error:
Using insomniac session-manager without extra-features

Traceback (most recent call last):
  File "start.py", line 4, in <module>
    insomniac.run(activation_code)
  File "/Users/Marco/Downloads/Insomniac-master/insomniac/__init__.py", line 30, in run
    insomniac_session.run()
  File "/Users/Marco/Downloads/Insomniac-master/insomniac/session.py", line 209, in run
    args = self.parse_args()
  File "/Users/Marco/Downloads/Insomniac-master/insomniac/session.py", line 135, in parse_args
    ok, args = parse_arguments(self.get_session_args(), self.starter_conf_file_path)
  File "/Users/Marco/Downloads/Insomniac-master/insomniac/params.py", line 46, in parse_arguments
    refresh_args_by_conf_file(args)
  File "/Users/Marco/Downloads/Insomniac-master/insomniac/params.py", line 72, in refresh_args_by_conf_file
    params = json.load(json_file)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 40 column 16 (char 1398)

**Comment by zubus** [comment]
Hi, try GramAddict ([https://github.com/GramAddict/bot/](https://github.com/GramAddict/bot/)) it is an open source (and 100% free!) Fork of Insomniac, it has this and many bugs already fixed and a great community ;)

**Comment by alexal1** [comment]
It means that your config file is incorrect
