### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by marco1m** [alexal1/Insomniac#318]
Using the demo command: python3 start.py I receive the following error. Everything has been setup correctly and until yesterday is was working just fine. If you could help me, i appreciate :)

[04/13 21:53:46] Checking your Internet speed to adjust the script speed, please wait for a minute...
[04/13 21:53:46] (use --no-speed-check to skip this check)
Traceback (most recent call last):
  File "start.py", line 4, in <module>
    insomniac.run(activation_code)
  File "/Users/Marco/Downloads/Insomniac-master/insomniac/__init__.py", line 30, in run
    insomniac_session.run()
  File "/Users/Marco/Downloads/Insomniac-master/insomniac/session.py", line 219, in run
    sleeper.update_random_sleep_range()
  File "/Users/Marco/Downloads/Insomniac-master/insomniac/sleeper.py", line 33, in update_random_sleep_range
    speed = _get_internet_speed()
  File "/Users/Marco/Downloads/Insomniac-master/insomniac/sleeper.py", line 61, in _get_internet_speed
    s = speedtest.Speedtest()
  File "/Users/Marco/Downloads/Insomniac-master/insomniac/tools/speedtest.py", line 964, in __init__
    self.get_config()
  File "/Users/Marco/Downloads/Insomniac-master/insomniac/tools/speedtest.py", line 1047, in get_config
    map(int, server_config['ignoreids'].split(','))
ValueError: invalid literal for int() with base 10: ''
MacBook-Pro-6:Insomniac-master Marco$

**Comment by zubus** [comment]
Hi, try GramAddict ([https://github.com/GramAddict/bot/](https://github.com/GramAddict/bot/)) it is an open source (and 100% free!) Fork of Insomniac, it has this and many bugs already fixed and a great community ;)

**Comment by alexal1** [comment]
FIxed in `v3.7.14`
