### ISSUE TITLE
Crashes after first start for any json file

### ISSUE THREAD

**Issue by niloy1187** [alexal1/Insomniac#322]
[04/18 15:04:54] Traceback (most recent call last):
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\device_facade.py", line 518, in scroll
    self.viewV2.scroll.toEnd(max_swipes=1)
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\_selector.py", line 574, in __call__
    return jsonrpc.scrollToEnd(selector, self.vertical,
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 435, in __call__
    return self.server._jsonrpc_retry_call(self.method, params,
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 442, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 514, in _jsonrpc_call
    raise err
uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error: <androidx.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=androidx.recyclerview.widget.RecyclerView, RESOURCE_ID=com.instagram.android:id/recycler_view], method: scrollToEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\safely_runner.py", line 14, in wrapper
    func(*args, **kwargs)
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\action_runners\interact\__init__.py", line 166, in job
    handle_hashtag(device_wrapper.get(),
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\action_runners\interact\action_handle_hashtag.py", line 216, in handle_hashtag
    extract_hashtag_profiles_and_interact(device,
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\action_runners\interact\action_handle_hashtag.py", line 249, in extract_hashtag_profiles_and_interact
    posts_view_list = PostsGridView(device).open_random_post()
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\views.py", line 842, in open_random_post
    posts_grid.scroll(DeviceFacade.Direction.BOTTOM)
  File "C:\Users\Niloy\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\device_facade.py", line 520, in scroll
    raise DeviceFacade.JsonRpcError(e)
insomniac.device_facade.DeviceFacade.JsonRpcError: -32001 Jsonrpc error: <androidx.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=androidx.recyclerview.widget.RecyclerView, RESOURCE_ID=com.instagram.android:id/recycler_view], method: scrollToEnd

**Comment by zubus** [comment]
Hi, try GramAddict ([https://github.com/GramAddict/bot/](https://github.com/GramAddict/bot/)) it is an open source (and 100% free!) Fork of Insomniac, it has this and many bugs already fixed and a great community ;)
