### ISSUE TITLE
Can't interact with users

### ISSUE THREAD

**Issue by tiagofabrica** [alexal1/Insomniac#33]
[06/26 23:12:57] Open Instagram app
[06/26 23:12:58] Sleep for 2 seconds
[06/26 23:13:00] Press profile
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 438, in wrapper
    return _method_obj(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 127, in __call__
    result = urllib2.urlopen(req, timeout=self.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insomniac.py", line 343, in <module>
    main()
  File "insomniac.py", line 71, in main
    session_state.my_username = get_my_username(device)
  File "/home/pi/Insomniac/action_get_my_username.py", line 10, in get_my_username
    profile_button.click.wait()
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 76, in __call__
    return self.func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 975, in _click
    return self.jsonrpc.clickAndWaitForNewWindow(self.selector, timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 442, in wrapper
    server.start(timeout=30)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 498, in start
    raise IOError("RPC server not started!")
OSError: RPC server not started!

I can't figure it out what the problem is, did anyone else had the same problem?

**Comment by Foncekar** [comment]
What is your adb version ?
`adb --version`

**Comment by alexal1** [comment]
Wrote a post describing what to do in such case: https://www.patreon.com/posts/problems-with-to-38702683. Hope it helps!

By the way, don't forget to donate if you like this project.
