### ISSUE TITLE
Issue at each launch

### ISSUE THREAD

**Issue by flodes80** [alexal1/Insomniac#342]
Hello,

I have an issue since many months that make Insomniac crashes every time.

It seems that the crash also make the dump of hierarchy crash so impossible to have it.

Here is the logs and some screenshots
[Insomniac.log](https://github.com/alexal1/Insomniac/files/6539734/Insomniac.log)
![screenshot](https://user-images.githubusercontent.com/12677853/119508286-ea9b5500-bd6f-11eb-875b-197617067e2f.jpg)
![screenshot](https://user-images.githubusercontent.com/12677853/119508305-ef600900-bd6f-11eb-982f-51c6c730db18.jpg)

**Comment by alexal1** [comment]
Seems that it's a uiautomator2 issue (https://github.com/openatx/uiautomator2/issues/207). Try to
1. Upgrade uiautomator2 to newer version `pip install uiautomator2 --upgrade`
2. If 1 won't help, try to run the script with the `--old` flag (runs on first version of uiautomator)

**Comment by flodes80** [comment]
Hi,

Tried first tip and didn't work.
The second give me this new error:

> ##########################################################
#                                                        #
#   _____                                 _              #
#  |_   _|                               (_)             #
#    | |  _ __  ___  ___  _ __ ___  _ __  _  __ _  ___   #
#    | | | '_ \/ __|/ _ \| '_ ` _ \| '_ \| |/ _` |/ __|  #
#   _| |_| | | \__ \ (_) | | | | | | | | | | (_| | (__   #
#  |_____|_| |_|___/\___/|_| |_| |_|_| |_|_|\__,_|\___|  #
#                                                        #
##########################################################

Insomniac v3.7.14

Hi! Since of v3.1.0 all core features in this project are free to use.
You may want to get more fine grained control over the bot via these features:
    - Filtering - skip unwanted accounts by various parameters
    - Scrapping - technique that makes interactions significantly safer and faster
    - Warmup - interact with your feed and Explore several minutes before session to behave more like a human
    - Working hours - the script will wait till specified hours before each session
    - Removing mass followers - automate "cleaning" you accountActivate by supporting our small team: https://insomniac-bot.com/activate/

Using insomniac session-manager without extra-features
[06/23 07:16:52] Checking your Internet speed to adjust the script speed, please wait for a minute...
[06/23 07:16:52] (use --no-speed-check to skip this check)
[06/23 07:17:15] Download speed 61.99 Mbit/s, upload speed 71.02 Mbit/s
[06/23 07:17:15] Sleep range will be from 1.00 to 3.00 seconds
Looking for ADB devices...
Connected devices via adb: 1. That's ok.
[06/23 07:17:17] Using uiautomator v1
[06/23 07:17:17] Instagram version: 193.0.0.45.120
[06/23 07:17:17] Running Insomniac with the "interact" action.
[06/23 07:17:17] Successful interactions limit per source: 70
[06/23 07:17:17] Interactions limit per source: 140
[06/23 07:17:17] Total likes limit: 175
[06/23 07:17:17] Total comments limit: 50

Caught an exception:

[06/23 07:17:20] Error - alive attribute not found!
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/session.py", line 255, in run
    self.start_session(args, device_wrapper, app_version, save_profile_info=True)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/session.py", line 177, in start_session
    device_wrapper.get().wake_up()
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/device_facade.py", line 214, in wake_up
    while not self.is_alive() and attempts < 5:
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/device_facade.py", line 207, in is_alive
    return self.deviceV1.alive()
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 589, in __getattr__
    raise AttributeError("%s attribute not found!" % attr)
AttributeError: alive attribute not found!

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/session.py", line 255, in run
    self.start_session(args, device_wrapper, app_version, save_profile_info=True)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/session.py", line 177, in start_session
    device_wrapper.get().wake_up()
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/device_facade.py", line 214, in wake_up
    while not self.is_alive() and attempts < 5:
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/device_facade.py", line 207, in is_alive
    return self.deviceV1.alive()
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 589, in __getattr__
    raise AttributeError("%s attribute not found!" % attr)
AttributeError: alive attribute not found!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Insomniac/start.py", line 4, in <module>
    insomniac.run(activation_code)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/__init__.py", line 30, in run
    insomniac_session.run()
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/session.py", line 281, in run
    save_crash(device_wrapper.get(), ex)
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/utils.py", line 162, in save_crash
    device.wake_up()
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/device_facade.py", line 214, in wake_up
    while not self.is_alive() and attempts < 5:
  File "/home/pi/.local/lib/python3.7/site-packages/insomniac/device_facade.py", line 207, in is_alive
    return self.deviceV1.alive()
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 589, in __getattr__
    raise AttributeError("%s attribute not found!" % attr)
AttributeError: alive attribute not found!
