### ISSUE TITLE
Crash when i try to interact with an user followers

### ISSUE THREAD

**Issue by Amai98** [alexal1/Insomniac#353]
Error - -32002 Client error: <> data: Selector [className='android.widget.TextView', clickable=True, textContains='Followers'], method: None
Traceback (most recent call last):
  File "C:\Users\giova\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\device_facade.py", line 473, in click
    self.viewV2.click(UI_TIMEOUT_LONG, offset=(x_offset, y_offset))
  File "C:\Users\giova\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2_selector.py", line 150, in click
    self.must_wait(timeout=timeout)
  File "C:\Users\giova\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2_selector.py", line 345, in must_wait
    raise UiObjectNotFoundError({'code': -32002, 'data': str(self.selector), 'method': 'wait'})
uiautomator2.exceptions.UiObjectNotFoundError: -32002 Client error: <> data: Selector [className='android.widget.TextView', clickable=True, textContains='Followers'], method: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\giova\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\safely_runner.py", line 19, in wrapper
    func(*args, **kwargs)
  File "C:\Users\giova\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\action_runners\interact__init__.py", line 149, in job
    handle_blogger(device_wrapper.get(),
  File "C:\Users\giova\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\action_runners\interact\action_handle_blogger.py", line 77, in handle_blogger
    followers_following_list_view = blogger_profile_view.navigate_to_followers()
  File "C:\Users\giova\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\views.py", line 1120, in navigate_to_followers
    followers_following_list_view.switch_to_tab(FollowersFollowingListView.Tab.FOLLOWERS)
  File "C:\Users\giova\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\views.py", line 1174, in switch_to_tab
    followers_tab.click()
  File "C:\Users\giova\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\device_facade.py", line 475, in click
    raise DeviceFacade.JsonRpcError(e)
insomniac.device_facade.DeviceFacade.JsonRpcError: -32002 Client error: <> data: Selector [className='android.widget.TextView', clickable=True, textContains='Followers'], method: None

**Comment by alexal1** [comment]
What Instagram version do you use?

**Comment by Amai98** [comment]
> What Instagram version do you use?

192.0.0.35.123

The latest version on playstore

**Comment by Amai98** [comment]
> What Instagram version do you use?

Same error with 191.1.0.41.124

**Comment by Amai98** [comment]
i get this error just with the new version of isomniac, no problem with the 3.7.12

**Comment by alexal1** [comment]
Ok, can you attach crash folder please?

**Comment by Amai98** [comment]
[Crash-2021-06-21-21-25-20.zip](https://github.com/alexal1/Insomniac/files/6695767/Crash-2021-06-21-21-25-20.zip)


> Ok, can you attach crash folder please?

**Comment by alexal1** [comment]
Will be fixed in `v3.7.15`

**Comment by Amai98** [comment]
> Will be fixed in `v3.7.15`

Thanks
