### ISSUE TITLE
BUG, does not open the followers list

### ISSUE THREAD

**Issue by tiagofabrica** [alexal1/Insomniac#37]
Traceback (most recent call last):
  File "insomniac.py", line 132, in _job_handle_bloggers
    handle_blogger(device, username, likes_count, follow_percentage, storage, _on_like, on_interaction)
  File "/home/pi/Insomniac/action_handle_blogger.py", line 23, in handle_blogger
    if not _open_user_followers(device, username):
  File "/home/pi/Insomniac/action_handle_blogger.py", line 64, in _open_user_followers
    followers_button.click.wait()
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 76, in __call__
    return self.func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 975, in _click
    return self.jsonrpc.clickAndWaitForNewWindow(self.selector, timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 458, in wrapper
    return _method_obj(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 135, in __call__
    "%s: %s" % (jsonresult["error"]["data"]["exceptionTypeName"], jsonresult["error"]["message"])
uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.LinearLayout, RESOURCE_ID=com.instagram.android:id/row_profile_header_followers_container]

Device: Nexus 5, initial I had it on a xiaomi, but i had to have the sim inserted to have some debug properties unlocked, so, i changed to the good old nexus 5. Don't know if the fact that i've changed the device somehow messed up

**Comment by alexal1** [comment]
> Don't know if the fact that i've changed the device somehow messed up

No, don't think so. Probably there's slightly different Instagram UI on this device/Android version. I'll need a `uiautomatorviewer`screenshot at the moment where the crash happens to find out the problem.

**Comment by tiagofabrica** [comment]
> > Don't know if the fact that i've changed the device somehow messed up
> 
> No, don't think so. Probably there's slightly different Instagram UI on this device/Android version. I'll need a `uiautomatorviewer`screenshot at the moment where the crash happens to find out the problem.

Hi, thanks a lot for the answers. 

I've updated the instagram app, and that solved that problem. It was indeed a different instagram UI,

but now i got a socket time out

---------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insomniac.py", line 343, in <module>
    main()
  File "insomniac.py", line 71, in main
    session_state.my_username = get_my_username(device)
  File "/home/pi/Insomniac/action_get_my_username.py", line 16, in get_my_username
    username = title_view.text
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 934, in __getattr__
    info = self.info
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 945, in info
    return self.jsonrpc.objInfo(self.selector)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 443, in wrapper
    return _JsonRPCMethod(url, method, timeout, False)(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 438, in wrapper
    return _method_obj(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 127, in __call__
    result = urllib2.urlopen(req, timeout=self.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

------

**Comment by alexal1** [comment]
Did you try everything from this post https://www.patreon.com/posts/problems-with-to-38702683?

**Comment by joezawinul** [comment]
No, but if you need help on a feature I will have spare time this week-end!

Let me know.

**Comment by alexal1** [comment]
This post contains steps to fix this error, feel free to reopen if they don't help.

> if you need help on a feature I will have spare time this week-end!

Sure, that'd be great!
