### ISSUE TITLE
Error - 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by o-grd** [alexal1/Insomniac#379]
-------- START: 2021-09-15 11:32:18.667635 --------
[09/15 11:32:20] Open Instagram app
[09/15 11:32:20] Error - 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\session.py", line 313, in run
    self.prepare_session_state(args, device_wrapper, app_version, save_profile_info=True)
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\session.py", line 263, in prepare_session_state
    hardban_indicator.detect_webview(device)
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\hardban_indicator.py", line 19, in detect_webview
    resumed_activity_output = execute_command("adb" + ("" if device_id is None else " -s " + device_id) +
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\utils.py", line 177, in execute_command
    err = cmd_res.stderr.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

Error - 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\session.py", line 313, in run
    self.prepare_session_state(args, device_wrapper, app_version, save_profile_info=True)
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\session.py", line 263, in prepare_session_state
    hardban_indicator.detect_webview(device)
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\hardban_indicator.py", line 19, in detect_webview
    resumed_activity_output = execute_command("adb" + ("" if device_id is None else " -s " + device_id) +
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\utils.py", line 177, in execute_command
    err = cmd_res.stderr.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by alexal1** [comment]
Fixed in v3.7.28
