### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by jonap339** [alexal1/Insomniac#38]
Dear, good afternoon.! My samsung s6 device after an internet outage started to throw the following error after entering the first follower to look at their photos. This is recurring, that is, it reaches the first follower and throws that message. Any ideas?

`python insomniac.py --interact comerennuevacordoba --likes-count 3 --total-likes-limit 200
`

`C:\Users\usuario\Desktop\samsung\Insomniac>python insomniac.py --interact comerennuevacordoba --likes-count 3 --total-likes-limit 200
Insomniac v1.5.1

Action: interact with @comerennuevacordoba

-------- START: 2020-06-28 16:26:17.618545 --------
Open Instagram app
Sleep for 2 seconds
Press profile
Hello, @bokurajeanscba

Handle @comerennuevacordoba
Press search
Open user @comerennuevacordoba
Open @comerennuevacordoba followers
Iterate over visible followers
@eltallerdeltequenio: interact
Sleep for 4 seconds
Scroll down to see more photos.
Screenshot taken and saved as Crash-2020-06-28-16-31-26.png

TOTAL
Completed sessions: 0
Total duration: 0:05:12.256446
Total interactions: 0
Successful interactions: 0
Total likes: 0
Total followed: 0
Total unfollowed: 0
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1332, in getresponse
    response.begin()
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insomniac.py", line 342, in <module>
    main()
  File "insomniac.py", line 77, in main
    _job_handle_bloggers(device,
  File "insomniac.py", line 152, in _job_handle_bloggers
    raise e
  File "insomniac.py", line 133, in _job_handle_bloggers
    handle_blogger(device, username, likes_count, follow_percentage, storage, _on_like, on_interaction)
  File "C:\Users\usuario\Desktop\samsung\Insomniac\action_handle_blogger.py", line 26, in handle_blogger
    _iterate_over_followers(device, interaction, storage, on_interaction, is_myself)
  File "C:\Users\usuario\Desktop\samsung\Insomniac\action_handle_blogger.py", line 120, in _iterate_over_followers
    interaction_succeed, followed = interaction(device, username=username, can_follow=can_follow)
  File "C:\Users\usuario\Desktop\samsung\Insomniac\action_handle_blogger.py", line 164, in _interact_with_user
    if not _scroll_profile(device):
  File "C:\Users\usuario\Desktop\samsung\Insomniac\action_handle_blogger.py", line 256, in _scroll_profile
    profile_tabs_container_top = profile_tabs_container.bounds['top']
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator\__init__.py", line 934, in __getattr__
    info = self.info
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator\__init__.py", line 945, in info
    return self.jsonrpc.objInfo(self.selector)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator\__init__.py", line 443, in wrapper
    return _JsonRPCMethod(url, method, timeout, False)(*args, **kwargs)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator\__init__.py", line 438, in wrapper
    return _method_obj(*args, **kwargs)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator\__init__.py", line 115, in __call__
    res = self.pool.urlopen("POST",
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=9009): Read timed out. (read timeout=90)

C:\Users\usuario\Desktop\samsung\Insomniac>`

I already tried everything, I even did a full reset and everything remains the same, it goes into the first follower and dies there. The strange thing is that the rest of my devices work perfectly.

Suggestions?

**Comment by alexal1** [comment]
> The strange thing is that the rest of my devices work perfectly.

1. Didn't this device fall asleep?
2. Probably slightly different UI on this model/Android version. I'll need a `uiautomatorviewer` screenshot on the place where it crashed to find out the problem.

**Comment by jonap339** [comment]
Alex, I think it's the account. Try the same account on another device and the same thing happens on that other device. I do not understand why this can happen, it will not be a form of instagram blocking? It happens with the account, not with the device.

**Comment by jonap339** [comment]
Today I tried again. It did less than 10 likes and then stopped working again. Attached screenshot with UiAutomatorviewer. I think if this is an instagram lock we are in trouble. Let's follow this case, as it can be a big problem! Regards!
[ERR.zip](https://github.com/alexal1/Insomniac/files/4845547/ERR.zip)

**Comment by alexal1** [comment]
`git pull` to get the latest version, please: hard to debug when there's an old code.

> I think if this is an instagram lock we are in trouble

That would be strange to block only specific action, leave others to work and not showing "Account blocked" window. But that account-connection is strange of course. Maybe that happens on this particular user "eltallerdeltequenio"? What about other profiles?

**Comment by alexal1** [comment]
Can it be because of multiple devices connected at once? Theoretically adb works through single port and can be overloaded

**Comment by jonap339** [comment]
Alex, I'm already running the latest insomniac update. As you will see in the registry, enter the first follower, and die there. The problem persists. I attach the error and the screenshot with UiAutomatorViewer.
Answering your questions:
1- No, the mobile did not fall asleep since I have it next to it.
2- Attached the screenshot for you to check where it was blocked.
3- The problem is the account, enter the first follower, whatever it is, and it is blocked.
4- I tried to run only that device and it hangs the same. I don't think it's an overload problem.

[Crash.zip](https://github.com/alexal1/Insomniac/files/4848317/Crash.zip)

**Comment by alexal1** [comment]
@jonap339 check please

**Comment by jonap339** [comment]
@alexal1 as we could verify, still does not move :( Please let me know what you need.! :(

**Comment by alexal1** [comment]
@jonap339 committed to the same branch, waiting for your response.

**Comment by alexal1** [comment]
Finally merged PR #43
