### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by quintendewilde** [alexal1/Insomniac#39]
```
 Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 438, in wrapper
    return _method_obj(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 135, in __call__
    "%s: %s" % (jsonresult["error"]["data"]["exceptionTypeName"], jsonresult["error"]["message"])
uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.LinearLayout, RESOURCE_ID=com.instagram.android:id/row_profile_header_followers_container]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insomniac.py", line 132, in _job_handle_bloggers
    handle_blogger(device, username, likes_count, follow_percentage, storage, _on_like, on_interaction)
  File "/home/pi/Insomniac/action_handle_blogger.py", line 23, in handle_blogger
    if not _open_user_followers(device, username):
  File "/home/pi/Insomniac/action_handle_blogger.py", line 63, in _open_user_followers
    followers_button.click.wait()
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 76, in __call__
    return self.func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 975, in _click
    return self.jsonrpc.clickAndWaitForNewWindow(self.selector, timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 458, in wrapper
    return _method_obj(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 135, in __call__
    "%s: %s" % (jsonresult["error"]["data"]["exceptionTypeName"], jsonresult["error"]["message"])
uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.LinearLayout, RESOURCE_ID=com.instagram.android:id/row_profile_header_followers_container]

```

![Crash-2020-06-29-20-31-59](https://user-images.githubusercontent.com/6031569/86042960-3fdbc300-ba48-11ea-98bb-952e0c567070.png)

**Comment by alexal1** [comment]
Checked this profile on my device, works fine.
Does it happen each time or only once? If each time, I'll need a `uiautomatorviewer` screenshot to fix this problem.
