### ISSUE TITLE
Didn't find tab PROFILE in the tab bar... Maybe English language is not set!?

### ISSUE THREAD

**Issue by konstantin-saetskiy-gismart** [alexal1/Insomniac#399]
Latest Incomniac, instagram v. 195. Crash zip: https://filebin.net/prpuuralb9vkcl1i/Crash-2021-10-24-12-58-26.zip

> Error - 
> Traceback (most recent call last):
>   File "/home/pi/.local/lib/python3.7/site-packages/insomniac/action_get_my_profile_info.py", line 9, in get_my_profile_info
>     profile_view = TabBarView(device).navigate_to_profile()
>   File "/home/pi/.local/lib/python3.7/site-packages/insomniac/views.py", line 140, in navigate_to_profile
>     self.navigate_to(TabBarTabs.PROFILE)
>   File "/home/pi/.local/lib/python3.7/site-packages/insomniac/views.py", line 203, in navigate_to
>     raise LanguageNotEnglishException()
> insomniac.views.LanguageNotEnglishException
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/pi/.local/lib/python3.7/site-packages/insomniac/session.py", line 313, in run
>     self.prepare_session_state(args, device_wrapper, app_version, save_profile_info=True)
>   File "/home/pi/.local/lib/python3.7/site-packages/insomniac/session.py", line 267, in prepare_session_state
>     self.session_state.my_following_count = get_my_profile_info(device, self.username)
>   File "/home/pi/.local/lib/python3.7/site-packages/insomniac/action_get_my_profile_info.py", line 29, in get_my_profile_info
>     switch_to_english(device)
>   File "/home/pi/.local/lib/python3.7/site-packages/insomniac/navigation.py", line 36, in switch_to_english
>     navigate(device, TabBarTabs.PROFILE, switch_to_english_on_exception=False)
>   File "/home/pi/.local/lib/python3.7/site-packages/insomniac/navigation.py", line 12, in navigate
>     raise ex
>   File "/home/pi/.local/lib/python3.7/site-packages/insomniac/navigation.py", line 9, in navigate
>     TabBarView(device).navigate_to(tab)
>   File "/home/pi/.local/lib/python3.7/site-packages/insomniac/views.py", line 203, in navigate_to
>     raise LanguageNotEnglishException()
> insomniac.views.LanguageNotEnglishException
>

**Comment by EnkhAmar** [comment]
Hi @konstantin-saetskiy-gismart , Did you solve this issue?

**Comment by konstantin-saetskiy-gismart** [comment]
> Hi @konstantin-saetskiy-gismart , Did you solve this issue?

Hi! No
