### ISSUE TITLE
BUG when see videos of 0-3 sec on feed

### ISSUE THREAD

**Issue by castelolmcb** [alexal1/Insomniac#40]
In my country it is common to post short videos in the feed with 0-3 seconds (GIF converted to video). When the code sees this type of post it crashes and fails to like.

![Crash-2020-06-29-18-34-23](https://user-images.githubusercontent.com/51883674/86059461-2b43fe80-ba39-11ea-8874-af7e68a12623.png)

CDM:

Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1332, in getresponse
    response.begin()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insomniac.py", line 351, in <module>
    main()
  File "insomniac.py", line 79, in main
    _job_handle_bloggers(device,
  File "insomniac.py", line 157, in _job_handle_bloggers
    raise e
  File "insomniac.py", line 137, in _job_handle_bloggers
    handle_blogger(device, username, likes_count, follow_percentage, storage, _on_like, on_interaction)
  File "C:\Users\xxxx\Desktop\Python\Insomniac-master\action_handle_blogger.py", line 27, in handle_blogger
    _iterate_over_followers(device, interaction, storage, on_interaction, is_myself)
  File "C:\Users\xxxx\Desktop\Python\Insomniac-master\action_handle_blogger.py", line 127, in _iterate_over_followers
    interaction_succeed, followed = interaction(device, username=username, can_follow=can_follow)
  File "C:\Users\xxxx\Desktop\Python\Insomniac-master\action_handle_blogger.py", line 185, in _interact_with_user
    if not _open_photo_and_like(device, row, column, on_like):
  File "C:\Users\xxxx\Desktop\Python\Insomniac-master\action_handle_blogger.py", line 227, in _open_photo_and_like
    action_bar_bottom = action_bar.bounds['bottom']
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator\__init__.py", line 934, in __getattr__
    info = self.info
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator\__init__.py", line 945, in info
    return self.jsonrpc.objInfo(self.selector)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator\__init__.py", line 443, in wrapper
    return _JsonRPCMethod(url, method, timeout, False)(*args, **kwargs)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator\__init__.py", line 438, in wrapper
    return _method_obj(*args, **kwargs)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator\__init__.py", line 115, in __call__
    res = self.pool.urlopen("POST",
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=9008): Read timed out. (read timeout=90)

**Comment by alexal1** [comment]
This post must help: https://www.patreon.com/posts/problems-with-to-38702683
If you try all steps from this post and it still doesn't work, reopen please.
