### ISSUE TITLE
Helpppppp

### ISSUE THREAD

**Issue by AnantTan** [alexal1/Insomniac#411]
Error - 'NoneType' object has no attribute 'count_scrapped_profiles_for_interaction' Traceback (most recent call last): File "/home/kali/Insomniac-master/insomniac/session.py", line 316, in run self.storage = InsomniacStorage(self.session_state.my_username, args) File "/home/kali/Insomniac-master/insomniac/storage.py", line 158, in __init__ count_from_scrapping = self.profile.count_scrapped_profiles_for_interaction() AttributeError: 'NoneType' object has no attribute 'count_scrapped_profiles_for_interaction'

**Comment by AnantTan** [comment]
Fixed ! just use the version recomended by Alexal. Newer versions causing problems.
