### ISSUE TITLE
Error running bot

### ISSUE THREAD

**Issue by simonwdr** [alexal1/Insomniac#418]
Just tested it with a fresh account and the test command "python3 start.py --interact @natgeo"
`D:\FollowBot\Isomniac>python3 start.py --interact @natgeo

##########################################################
#                                                        #
#   _____                                 _              #
#  |_   _|                               (_)             #
#    | |  _ __  ___  ___  _ __ ___  _ __  _  __ _  ___   #
#    | | | '_ \/ __|/ _ \| '_ ` _ \| '_ \| |/ _` |/ __|  #
#   _| |_| | | \__ \ (_) | | | | | | | | | | (_| | (__   #
#  |_____|_| |_|___/\___/|_| |_| |_|_| |_|_|\__,_|\___|  #
#                                                        #
##########################################################

Engine v3.7.28

Hi! Since of v3.1.0 all core features in this project are free to use.
You may want to get more fine grained control over the bot via these features:
    - Filtering - skip unwanted accounts by various parameters
    - Scrapping - technique that makes interactions significantly safer and faster
    - Warmup - interact with your feed and Explore several minutes before session to behave more like a human
    - Working hours - the script will wait till specified hours before each session
    - Removing mass followers - automate "cleaning" your account
Activate by supporting our small team: https://insomniac-bot.com/activate/

Using insomniac session-manager without extra-features
[02/05 20:09:58] Checking your Internet speed to adjust the script speed, please wait for a minute...
[02/05 20:09:58] (use --no-speed-check to skip this check)
[02/05 20:10:20] Download speed 8.82 Mbit/s, upload speed 13.39 Mbit/s
[02/05 20:10:20] Sleep range will be from 1.93 to 4.85 seconds
Looking for ADB devices...
Connected devices via adb: 1. That's ok.
[02/05 20:10:21] Using uiautomator v2
[I 220205 20:10:21 init:155] uiautomator2 version: 2.7.3
[02/05 20:10:21] Instagram version: 220.0.0.16.115

IG version (220.0.0.16.115) is newer than latest supported (195.0.0.31.123).
Please uninstall IG and download recommended apk from here:
https://insomniac-bot.com/get_latest_supported_ig_apk/

[02/05 20:10:21] Executing "interact" action.
[02/05 20:10:21] Successful interactions limit per source: 70
[02/05 20:10:21] Interactions limit per source: 140
[02/05 20:10:21] Total likes limit: 1000
[02/05 20:10:21] Total comments limit: 50
[02/05 20:10:21] Error - 'Session or Device' object has no attribute '_is_alive'
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\__init__.py", line 1616, in __getattr__
    return getattr(self._default_session, attr)
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\session.py", line 642, in __getattr__
    raise AttributeError(f"Session object has no attribute '{key}'")
AttributeError: Session object has no attribute '_is_alive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\session.py", line 313, in run
    self.prepare_session_state(args, device_wrapper, app_version, save_profile_info=True)
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\session.py", line 255, in prepare_session_state
    device.wake_up()
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\device_facade.py", line 217, in wake_up
    while not self.is_alive() and attempts < 5:
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\device_facade.py", line 212, in is_alive
    return self.deviceV2._is_alive()
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\__init__.py", line 1618, in __getattr__
    raise AttributeError(
AttributeError: 'Session or Device' object has no attribute '_is_alive'

[02/05 20:10:21] Could not save crash after an error. Crash-save-error: 'Session or Device' object has no attribute '_is_alive'
[02/05 20:10:21] Error - 'Session or Device' object has no attribute '_is_alive'
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\__init__.py", line 1616, in __getattr__
    return getattr(self._default_session, attr)
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\session.py", line 642, in __getattr__
    raise AttributeError(f"Session object has no attribute '{key}'")
AttributeError: Session object has no attribute '_is_alive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\session.py", line 313, in run
    self.prepare_session_state(args, device_wrapper, app_version, save_profile_info=True)
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\session.py", line 255, in prepare_session_state
    device.wake_up()
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\device_facade.py", line 217, in wake_up
    while not self.is_alive() and attempts < 5:
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\device_facade.py", line 212, in is_alive
    return self.deviceV2._is_alive()
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\__init__.py", line 1618, in __getattr__
    raise AttributeError(
AttributeError: 'Session or Device' object has no attribute '_is_alive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\__init__.py", line 1616, in __getattr__
    return getattr(self._default_session, attr)
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\session.py", line 642, in __getattr__
    raise AttributeError(f"Session object has no attribute '{key}'")
AttributeError: Session object has no attribute '_is_alive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\utils.py", line 193, in save_crash
    device.wake_up()
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\device_facade.py", line 217, in wake_up
    while not self.is_alive() and attempts < 5:
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\device_facade.py", line 212, in is_alive
    return self.deviceV2._is_alive()
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\__init__.py", line 1618, in __getattr__
    raise AttributeError(
AttributeError: 'Session or Device' object has no attribute '_is_alive'

[02/05 20:10:21] Close Instagram app com.instagram.android
C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\__init__.py:555: RuntimeWarning: uiautomator2 is not reponding, restart uiautomator2 automatically
  warnings.warn(
[D 220205 20:10:22 __init__:774] restart-uiautomator since "UiAutomator stopped"
[D 220205 20:10:22 __init__:844] Device: OnePlus, 7d2a6a00
[D 220205 20:10:22 __init__:854] kill process(ps): uiautomator
[D 220205 20:10:23 __init__:867] uiautomator-v2 is starting ... left: 40.0s
[D 220205 20:10:24 __init__:867] uiautomator-v2 is starting ... left: 39.0s
[D 220205 20:10:25 __init__:867] uiautomator-v2 is starting ... left: 37.9s
[D 220205 20:10:25 __init__:774] restart-uiautomator since "UiAutomator stopped"
[D 220205 20:10:25 __init__:844] Device: OnePlus, 7d2a6a00
[D 220205 20:10:25 __init__:854] kill process(ps): uiautomator
[D 220205 20:10:25 __init__:826] grant permissions
[D 220205 20:10:26 __init__:867] uiautomator-v2 is starting ... left: 40.0s
[D 220205 20:10:27 __init__:867] uiautomator-v2 is starting ... left: 39.0s
[D 220205 20:10:28 __init__:867] uiautomator-v2 is starting ... left: 37.9s
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\__init__.py", line 553, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\__init__.py", line 606, in jsonrpc_call
    raise GatewayError(
uiautomator2.exceptions.GatewayError: uiautomator2.GatewayError(gateway error, time used 0.0s)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\device_facade.py", line 558, in exists
    return self.viewV2.exists(UI_TIMEOUT_SHORT if quick else UI_TIMEOUT_LONG)
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\utils.py", line 107, in __call__
    return self.uiobject.wait(timeout=timeout)
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\session.py", line 944, in wait
    return self.jsonrpc.waitForExists(self.selector,
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\__init__.py", line 546, in __call__
    return self.server.jsonrpc_retry_call(self.method, params,
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\__init__.py", line 559, in jsonrpc_retry_call
    self.reset_uiautomator("UiAutomator stopped")
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\__init__.py", line 790, in reset_uiautomator
    return self.reset_uiautomator(reason=reason,
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\__init__.py", line 790, in reset_uiautomator
    return self.reset_uiautomator(reason=reason,
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uiautomator2\__init__.py", line 767, in reset_uiautomator
    raise EnvironmentError(
OSError: [WinError adb shell am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner] UiAutomator stopped: 'https://github.com/openatx/uiautomator2/wiki/Common-issues'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FollowBot\Isomniac\start.py", line 4, in <module>
    insomniac.run(activation_code)
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\__init__.py", line 33, in run
    insomniac_session.run()
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\session.py", line 348, in run
    self.end_session(device_wrapper, with_app_closing=self.should_close_app_after_session(args, device_wrapper))
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\session.py", line 273, in end_session
    close_instagram_and_system_dialogs(device_wrapper.get())
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\navigation.py", line 46, in close_instagram_and_system_dialogs
    DialogView(device).close_not_responding_dialog_if_visible()
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\views.py", line 1495, in close_not_responding_dialog_if_visible
    if self._click_close_app():
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\views.py", line 1503, in _click_close_app
    if close_app_button.exists():
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\insomniac\device_facade.py", line 559, in exists
    except uiautomator2.JSONRPCError as e:
AttributeError: module 'uiautomator2' has no attribute 'JSONRPCError'`

**Comment by alexal1** [comment]
> IG version (220.0.0.16.115) is newer than latest supported (195.0.0.31.123)

**Comment by alexal1** [comment]
Also make sure that uiautomator2 is the latest

**Comment by elabdi** [comment]
i still face the same issues with the supported version 195.0.0.31.123, all the time the same error happens Jsonrpc and the phone disconnected from adb.

**Comment by alexal1** [comment]
Try to uninstall the ATX app on the phone

**Comment by larrybird1** [comment]
Hello, im having the same issue
i tried to uninstall atx, but reinstalls automatically

how to get rid if this error

  File "C:\Users\Administrator\pyproj\my_env\lib\site-packages\insomniac\device_facade.py", line 493, in click
    except uiautomator2.JSONRPCError as e:
AttributeError: module 'uiautomator2' has no attribute 'JSONRPCError'
