### ISSUE TITLE
[Bug]Installation on M1 pro failed

### ISSUE THREAD

**Issue by moharnab123saikia** [alexal1/Insomniac#420]
I was trying to install the library on my 14 inch M1 mac with an M1 pro chip.

**Syetem Details:**

- Python Version: Python 3.8.9
- ProductName:	macOS
- ProductVersion:	12.1
- BuildVersion:	21C52

**Here is the output:**

```terminal
m@Ms-MacBook-Pro Insomniac % python3 -m pip install insomniac
Defaulting to user installation because normal site-packages is not writeable
Collecting insomniac
  Using cached insomniac-3.7.28-py3-none-any.whl (2.1 MB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting uiautomator2
  Downloading uiautomator2-2.16.14-py3-none-any.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 8.9 MB/s eta 0:00:00
Collecting croniter
  Downloading croniter-1.3.4-py2.py3-none-any.whl (17 kB)
Collecting sourcedefender
  Using cached sourcedefender-7.1.67.tar.gz (8.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/vg/3y0j8p9s22zft3z9gpdwxs3w0000gn/T/pip-install-f7v8gn62/sourcedefender_85403755fe54466e970ebd16aecef3cf/setup.py", line 135, in <module>
          package_data={'sourcedefender': get_package_data_list()},
        File "/private/var/folders/vg/3y0j8p9s22zft3z9gpdwxs3w0000gn/T/pip-install-f7v8gn62/sourcedefender_85403755fe54466e970ebd16aecef3cf/setup.py", line 83, in get_package_data_list
          raise RuntimeError(
      RuntimeError:
      
      
      
      
      Please contact hello@sourcedefender.co.uk for assistance
      Path: src/ext/darwin64/arm64/38
      
      
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by alexal1** [comment]
Try `pip install --upgrade pip`
