### ISSUE TITLE
Error on v380

### ISSUE THREAD

**Issue by yurilimajr** [alexal1/Insomniac#423]
Even though Instagram was opened successfully it shows me this message on the terminal:

[03/10 10:03:38] Instagram is not yet opened, waiting...

And it keeps looping on this.

Connection is ok, also did a new installation on insomniac.

Is there a way to install an earlier version?

**Comment by alexal1** [comment]
`python3 -m pip install insomniac==<your version here>`

**Comment by yurilimajr** [comment]
I was able to install an earlier version, but it still does a network check and does not identify instagram is opened (even though it is).

Any suggestion? (maybe disabling network check? did not see a parameter for this though, using Json config file)

**Comment by alexal1** [comment]
Uninstall ADBKeyboard app on your device as well

**Comment by yurilimajr** [comment]
Still wasn't able to make it work, anyway, went back to 3.8 version and got this error (instagram is opened successfully): 

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1494, in _readerthread
    buffer.append(fh.read())
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 8: invalid continuation byte
[03/11 17:15:30] Instagram is not yet opened, waiting...
