### ISSUE TITLE
New version dont open Instagram app

### ISSUE THREAD

**Issue by SithX** [alexal1/Insomniac#425]
`[03/14 17:07:16] Open Instagram app with network check
[03/14 17:07:22] Instagram is not yet opened, waiting...
[03/14 17:07:38] Instagram is not yet opened, waiting...
[03/14 17:07:54] Instagram is not yet opened, waiting...
[03/14 17:08:10] Instagram is not yet opened, waiting...
[03/14 17:08:25] Instagram is not yet opened, waiting...
[03/14 17:08:40] Instagram is not yet opened, waiting...
[03/14 17:08:55] Instagram is not yet opened, waiting...
[03/14 17:09:11] Instagram is not yet opened, waiting...
[03/14 17:09:27] Instagram is not yet opened, waiting...
`

**Comment by alexal1** [comment]
Provide a full log pls

**Comment by SithX** [comment]
sing insomniac session-manager without extra-features
Looking for ADB devices...
Connected devices via adb: 1. That's ok.
[03/14 17:46:31] Installing ADB Keyboard to enable typewriting...
[03/14 17:46:45] Using uiautomator v2
[03/14 17:46:45] Instagram version: 195.0.0.31.123
[03/14 17:46:45] Executing "interact" action.
[03/14 17:46:45] Successful interactions limit per source: 70
[03/14 17:46:45] Interactions limit per source: 140
[03/14 17:46:45] Total likes limit: 50
[03/14 17:46:45] Total interactions limit: 120
[03/14 17:46:45] Total successful-interactions limit: 58
[03/14 17:46:45] Total story-watches limit: 101
[03/14 17:46:45] Total comments limit: 50
[03/14 17:46:45] Total get-profile limit: 351
[03/14 17:46:45] Session max-length (minutes): 52

-------- START: 2022-03-14 17:46:45.599938 --------
[03/14 17:46:45] Open Instagram app with network check
[03/14 17:46:52] Instagram is not yet opened, waiting...
[03/14 17:47:07] Instagram is not yet opened, waiting...
[03/14 17:47:22] Instagram is not yet opened, waiting...
[03/14 17:47:37] Instagram is not yet opened, waiting...
[03/14 17:47:53] Instagram is not yet opened, waiting...

**Comment by yurilimajr** [comment]
Similar problem here:

Same problem here:

Exception in thread Thread-8 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\Yuri\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Yuri\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Yuri\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1494, in _readerthread
    buffer.append(fh.read())
  File "C:\Users\Yuri\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 8: invalid continuation byte
[03/14 20:21:20] Instagram is not yet opened, waiting...

**Comment by alexal1** [comment]
As a quick fix you can download the repo and edit navigation.py file:
write `return open_instagram(device_id, app_id)`
on line 50 https://github.com/alexal1/Insomniac/blob/7bb4c55731afbd3bd7210b27189713ab3167d6d6/insomniac/navigation.py#L50

**Comment by SithX** [comment]
> As a quick fix you can download the repo and edit navigation.py file: write `return open_instagram(device_id, app_id)` on line 50
> 
> https://github.com/alexal1/Insomniac/blob/7bb4c55731afbd3bd7210b27189713ab3167d6d6/insomniac/navigation.py#L50

Where is the folder? in raspberrypi?

**Comment by yurilimajr** [comment]
Solved for me, thanks @alexal1

**Comment by SithX** [comment]
I can't find the directory to modify the file in raspberrypi, can someone help me?

**Comment by Booleboole** [comment]
> I can't find the directory to modify the file in raspberrypi, can someone help me?

file s in your home directory in a hidden directory

.local/lib/python3.7/site-packages/insomniac

then modify via nano or another editor

**Comment by alexal1** [comment]
Could you please help me investigate this?

What's the output of `adb shell dumpsys activity | grep 'mResumedActivity'` _after_ instagram is opened?

**Comment by robium-max** [comment]
I have a same issue.
For


> Could you please help me investigate this?
> 
> What's the output of `adb shell dumpsys activity | grep 'mResumedActivity'` _after_ instagram is opened?

I have the samme issu, when i run the bot :
Engine v3.8.2

Hi! Since of v3.1.0 all core features in this project are free to use.
You may want to get more fine grained control over the bot via these features:
    - Filtering - skip unwanted accounts by various parameters
    - Scrapping - technique that makes interactions significantly safer and faster
    - Warmup - interact with your feed and Explore several minutes before session to behave more like a human
    - Working hours - the script will wait till specified hours before each session
    - Removing mass followers - automate "cleaning" your account
Activate by supporting our small team: https://insomniac-bot.com/activate/

Using insomniac session-manager without extra-features
[04/17 10:36:45] Checking your Internet speed to adjust the script speed, please wait for a minute...
[04/17 10:36:45] (use --no-speed-check to skip this check)
[04/17 10:37:07] Download speed 14.68 Mbit/s, upload speed 40.79 Mbit/s
[04/17 10:37:07] Sleep range will be from 1.00 to 3.00 seconds
Looking for ADB devices...
Connected devices via adb: 1. That's ok.
[04/17 10:37:07] Using uiautomator v2
[04/17 10:37:08] Instagram version: 195.0.0.31.123
[04/17 10:37:08] Sleep time (min) before repeat: 0.00
[04/17 10:37:08] Executing "interact" action.
[04/17 10:37:08] Successful interactions limit per source: 8
[04/17 10:37:08] Interactions limit per source: 12
[04/17 10:37:08] Total likes limit: 53
[04/17 10:37:08] Total interactions limit: 117
[04/17 10:37:08] Total successful-interactions limit: 50
[04/17 10:37:08] Total comments limit: 50
[04/17 10:37:08] Total get-profile limit: 392
[04/17 10:37:08] Session max-length (minutes): 59

------- START: 2022-04-17 10:37:08.379402 --------
[04/17 10:37:08] Open Instagram app with network check
[04/17 10:37:13] Instagram is not yet opened, waiting...
[04/17 10:37:29] Instagram is not yet opened, waiting...
[04/17 10:37:44] Instagram is not yet opened, waiting...
[04/17 10:37:59] Instagram is not yet opened, waiting...
[04/17 10:38:14] Instagram is not yet opened, waiting...
[04/17 10:38:29] Instagram is not yet opened, waiting...
[04/17 10:38:45] Instagram is not yet opened, waiting...
[04/17 10:39:00] Instagram is not yet opened, waiting...
[04/17 10:39:15] Instagram is not yet opened, waiting...
[04/17 10:39:30] Open Instagram app with network check
[04/17 10:39:30] Didn't work :(
[04/17 10:39:30] Open Instagram app
[04/17 10:39:32] Closing keyboard...
[04/17 10:39:32] The device keyboard is already closed.
[04/17 10:39:38] Sleep for 2.72 seconds
[04/17 10:39:41] Refreshing your profile status...
[04/17 10:39:42] Sleep for 2.60 seconds
[04/17 10:39:46] Hello, @.......

While on the phone screen, ADBkeyboard trying to open the Instagram and says "no internet connection" flashing between an orange and a white page (under ADBkeyboard) but when i open the Insta manually it's working fine also the browsers.

Here some pics about the issue:

https://ibb.co/JB2XXY7
https://ibb.co/PN43BFv

After a couple of trying it's connect back and work properly.

Does your keyboard need any network to work properly?

This is my error output after the BOT opened the Insta:
db shell dumpsys activity | grep 'mResumedActivity'
    mResumedActivity: ActivityRecord{f0783f u0 com.alexal1.adbkeyboard/com.alexal1.starter.StarterActivity t769}

On the phone im running LineageOS.
