### ISSUE TITLE
Issue with v3.8.1

### ISSUE THREAD

**Issue by yurilimajr** [alexal1/Insomniac#426]
Facing 2 issues:

1- New version opens instagram with network check but the terminal keeps on looping "Instagram is not yet opened, waiting"

2- Getting this utf-8 error below on the terminal:

-------- START: 2022-03-14 20:32:39.254997 --------
[03/14 20:32:39] Open Instagram app with network check
Exception in thread Thread-4 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\Yuri\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Yuri\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Yuri\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1494, in _readerthread
    buffer.append(fh.read())
  File "C:\Users\Yuri\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 8: invalid continuation byte
[03/14 20:32:44] Instagram is not yet opened, waiting...

**Comment by alexal1** [comment]
See quick fix in #425
