### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 11: invalid start byte

### ISSUE THREAD

**Issue by marcosalvadori** [alexal1/Insomniac#435]
```
Exception in thread Thread-103 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1494, in _readerthread
    buffer.append(fh.read())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 11: invalid start byte
```

@alexal1 i tried the issues for other similar problem, but cannot solve.
How can i solve this?

**Comment by alexal1** [comment]
Something strange. Try to update uiautomator, uiautomator2 and sourcedefender.

**Comment by marcosalvadori** [comment]
Many thanks @alexal1 semms it solved.
The problem remain but the bot continue 

`-------- START: 2022-06-03 13:17:54.882188 --------
[06/03 13:17:54] Open Instagram app with network check
Exception in thread Thread-101:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1475, in _readerthread
    buffer.append(fh.read())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 11: invalid start byte
[06/03 13:18:00] Didn't work :(
[06/03 13:18:00] Open Instagram app
[06/03 13:18:04] PROFILE tab is not opened, will try again.
[06/03 13:18:04] Sleep for 2.78 seconds
[06/03 13:18:08] Sleep for 2.59 seconds`

**Comment by marcosalvadori** [comment]
The problem is random during the execution. Bot stop activity avery sone minutes with similar error.

I try Python 3.9 and 3.10. My instagram version is the correct 195......

Some minutes ago, this:
`[06/03 13:49:24] Sleep for 4.05 seconds
[06/03 13:49:28] Iterate over visible likers.
[06/03 13:49:28] Iterated exactly the same likers twice, finish.
[06/03 13:49:28] Going back
[06/03 13:49:33] No likes, let's scroll down.
[06/03 13:49:36] Opening post likers
[06/03 13:49:36] List of likers is opened.
[06/03 13:49:36] Sleep for 2.07 seconds
[06/03 13:49:38] Iterate over visible likers.
[06/03 13:49:38] Iterated exactly the same likers twice, finish.
[06/03 13:49:38] Going back
[06/03 13:49:39] Same users iterated 2 times. It's either an end of the list or a softban. Anyway, let's finish.
Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)`

Any idea @alexal1 ?

**Comment by drogba72** [comment]
Hi,
I have the same error. Do you find how fix it please ?

Regards

**Comment by drogba72** [comment]
Update for this issue :

- I change the version of instagram and use the version who is recommended
- I change the langage in English
- I changed the navigation.py like the solution of issue #425.
