### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by MehrnazAmoon** [alexal1/Insomniac#441]
Hey I cant run the bot, in first stage when I call this command I see these error. Any idea?
 python3 start.py --interact @user amazingtrips-recent-likers --interactions-count 20-30 --likes-count 1-2 --follow-percentage 80 --repeat 160-220

Traceback (most recent call last):
  File "/Users/xx/Insomniac-master/start.py", line 4, in <module>
    insomniac.run(activation_code)
  File "/Users/xx/Insomniac-master/insomniac/__init__.py", line 33, in run
    insomniac_session.run()
  File "/Users/xx/Insomniac-master/insomniac/session.py", line 389, in run
    self.end_session(device_wrapper, with_app_closing=self.should_close_app_after_session(args, device_wrapper))
  File "/Users/xx/Insomniac-master/insomniac/session.py", line 314, in end_session
    close_instagram_and_system_dialogs(device_wrapper.get())
  File "/Users/xx/Insomniac-master/insomniac/navigation.py", line 88, in close_instagram_and_system_dialogs
    DialogView(device).close_not_responding_dialog_if_visible()
  File "/Users/xx/Insomniac-master/insomniac/views.py", line 1597, in close_not_responding_dialog_if_visible
    if self._click_close_app():
  File "/Users/xx/Insomniac-master/insomniac/views.py", line 1605, in _click_close_app
    if close_app_button.exists():
  File "/Users/xx/Insomniac-master/insomniac/device_facade.py", line 571, in exists
    return self.viewV2.exists(UI_TIMEOUT_SHORT if quick else UI_TIMEOUT_LONG)
  File "/Users/xxs/Insomniac-master/venv/lib/python3.10/site-packages/uiautomator2/utils.py", line 114, in __call__
    return self.uiobject.wait(timeout=timeout)
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/uiautomator2/_selector.py", line 314, in wait
    return self.jsonrpc.waitForExists(self.selector,
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/uiautomator2/__init__.py", line 475, in __call__
    return self.server._jsonrpc_retry_call(self.method, params,
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/uiautomator2/__init__.py", line 482, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/uiautomator2/__init__.py", line 508, in _jsonrpc_call
    res = self.http.post("/jsonrpc/0",
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/uiautomator2/__init__.py", line 223, in request
    self.__client._prepare_atx_agent()
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/uiautomator2/__init__.py", line 324, in _prepare_atx_agent
    self._setup_atx_agent()
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/uiautomator2/__init__.py", line 334, in _setup_atx_agent
    _initer.setup_atx_agent()
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/uiautomator2/init.py", line 351, in setup_atx_agent
    self.check_atx_agent_version()
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/uiautomator2/init.py", line 360, in check_atx_agent_version
    version = requests.get("http://%s:%d/version" %
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/xx/Insomniac-master/venv/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by JoydS** [comment]
Same problem here

**Comment by JoydS** [comment]
Actually I do :)
