### ISSUE TITLE
IG version (249.0.0.20.105) is newer than latest supported (195.0.0.31.123).

### ISSUE THREAD

**Issue by minsuh04** [alexal1/Insomniac#443]
----------------------------------------------------------------------------------------
IG version (249.0.0.20.105) is newer than latest supported (195.0.0.31.123).
Please uninstall IG and download recommended apk from here:
https://insomniac-bot.com/get_latest_supported_ig_apk/
Press ENTER to continue anyway...
----------------------------------------------------------------------------------------

I uninstalled the latest version and installed IG version 195.0.0.31.123 who is recommended from the link
but IG is not working on MEMU.
I can't even open the app as attached picture.

I attached the files.
What should I do? 

[insomniac_log-2022-09-15-18-57-18.log](https://github.com/alexal1/Insomniac/files/9574133/insomniac_log-2022-09-15-18-57-18.log)
[Crash-2022-09-15-18-58-43.zip](https://github.com/alexal1/Insomniac/files/9574152/Crash-2022-09-15-18-58-43.zip)
[Crash-2022-09-15-18-59-11.zip](https://github.com/alexal1/Insomniac/files/9574153/Crash-2022-09-15-18-59-11.zip)
![Capture](https://user-images.githubusercontent.com/48954011/190375875-2909f45d-6dca-4be0-8bdc-96613f527e29.JPG)

Engine v3.8.6

Hi! Since of v3.1.0 all core features in this project are free to use.
You may want to get more fine grained control over the bot via these features:

    - Filtering - skip unwanted accounts by various parameters
    - Scrapping - technique that makes interactions significantly safer and faster
    - Warmup - interact with your feed and Explore several minutes before session to behave more like a human
    - Working hours - the script will wait till specified hours before each session
    - Removing mass followers - automate "cleaning" your account
Activate by supporting our small team: https://insomniac-bot.com/activate/

Using insomniac session-manager without extra-features
[09/15 18:57:19] Checking your Internet speed to adjust the script speed, please wait for a minute...
[09/15 18:57:19] (use --no-speed-check to skip this check)
[09/15 18:57:46] Download speed 9.05 Mbit/s, upload speed 9.83 Mbit/s
[09/15 18:57:46] Sleep range will be from 2.13 to 5.19 seconds
Looking for ADB devices...
Connected devices via adb: 1. That's ok.
[09/15 18:57:46] Installing ADB Keyboard to enable typewriting...
[09/15 18:57:47] Using uiautomator v2
[09/15 18:57:47] Instagram version: 195.0.0.31.123
[09/15 18:57:49] Executing "interact" action.
[09/15 18:57:49] Successful interactions limit per source: 70
[09/15 18:57:49] Interactions limit per source: 140
[09/15 18:57:49] Total likes limit: 1000
[09/15 18:57:49] Total comments limit: 50
[09/15 18:57:49] 'grep' is not recognized as an internal or external command,
operable program or batch file.
[09/15 18:57:49] Open Instagram app with network check
[09/15 18:57:54] 'grep' is not recognized as an internal or external command,
operable program or batch file.
[09/15 18:57:54] Didn't work :(
[09/15 18:57:54] Open Instagram app
[09/15 18:57:55] Closing keyboard...
[09/15 18:57:55] The device keyboard is already closed.
[09/15 18:58:02] Closing keyboard...
[09/15 18:58:02] The device keyboard is already closed.
[09/15 18:58:07] Clearing the back stack...
[09/15 18:58:12] Cannot find back arrow in TabBarView, press hardware back
[09/15 18:58:13] Pressed back but nothing changed on the screen. Will try again.
[09/15 18:58:13] Sleep for 5.13 seconds
[09/15 18:58:23] Closing keyboard...
[09/15 18:58:23] The device keyboard is already closed.
[09/15 18:58:34] Cannot find back arrow in TabBarView, press hardware back
[09/15 18:58:35] Pressed back but nothing changed on the screen. Will try again.
[09/15 18:58:35] Sleep for 4.74 seconds
[09/15 18:58:41] Pressed back but nothing changed on the screen. Will try again.
[09/15 18:58:41] Sleep for 2.60 seconds
[09/15 18:58:43] Tried to press back 2 times with no success. Will proceed next...
[09/15 18:58:43] Error - Unexpected app state: want to go back but can't
Traceback (most recent call last):
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\action_get_my_profile_info.py", line 11, in get_my_profile_info
    profile_view = TabBarView(device).navigate_to_profile()
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\views.py", line 151, in navigate_to_profile
    self.navigate_to(TabBarTabs.PROFILE)
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\views.py", line 162, in navigate_to
    is_backstack_cleared = self._clear_backstack()
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\views.py", line 232, in _clear_backstack
    self.press_back_arrow()
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\views.py", line 88, in press_back_arrow
    raise RuntimeError("Unexpected app state: want to go back but can't")
RuntimeError: Unexpected app state: want to go back but can't

[09/15 18:58:43] Crash saved as "crashes/Crash-2022-09-15-18-58-43.zip".
[09/15 18:58:43] Please attach this file if you gonna report the crash at
[09/15 18:58:43] https://github.com/alexal1/Insomniac/issues

[09/15 18:58:43] Switching to English locale
[09/15 18:58:44] Closing keyboard...
[09/15 18:58:45] The device keyboard is already closed.
[09/15 18:58:51] Closing keyboard...
[09/15 18:58:51] The device keyboard is already closed.
[09/15 18:58:56] Clearing the back stack...
[09/15 18:59:01] Cannot find back arrow in TabBarView, press hardware back
[09/15 18:59:02] Pressed back but nothing changed on the screen. Will try again.
[09/15 18:59:02] Sleep for 2.36 seconds
[09/15 18:59:05] Pressed back but nothing changed on the screen. Will try again.
[09/15 18:59:05] Sleep for 5.07 seconds
[09/15 18:59:11] Tried to press back 2 times with no success. Will proceed next...
[09/15 18:59:11] Error - Unexpected app state: want to go back but can't
Traceback (most recent call last):
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\action_get_my_profile_info.py", line 11, in get_my_profile_info
    profile_view = TabBarView(device).navigate_to_profile()
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\views.py", line 151, in navigate_to_profile
    self.navigate_to(TabBarTabs.PROFILE)
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\views.py", line 162, in navigate_to
    is_backstack_cleared = self._clear_backstack()
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\views.py", line 232, in _clear_backstack
    self.press_back_arrow()
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\views.py", line 88, in press_back_arrow
    raise RuntimeError("Unexpected app state: want to go back but can't")
RuntimeError: Unexpected app state: want to go back but can't

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\session.py", line 354, in run
    self.prepare_session_state(args, device_wrapper, app_version, save_profile_info=True)
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\session.py", line 308, in prepare_session_state
    self.session_state.my_following_count = get_my_profile_info(device, self.username)
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\action_get_my_profile_info.py", line 31, in get_my_profile_info
    switch_to_english(device)
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\navigation.py", line 36, in switch_to_english
    navigate(device, TabBarTabs.PROFILE, switch_to_english_on_exception=False)
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\navigation.py", line 9, in navigate
    TabBarView(device).navigate_to(tab)
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\views.py", line 162, in navigate_to
    is_backstack_cleared = self._clear_backstack()
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\views.py", line 232, in _clear_backstack
    self.press_back_arrow()
  File "C:\Users\hanyangeng\Downloads\Insomniac-master2\Insomniac-master\insomniac\views.py", line 88, in press_back_arrow
    raise RuntimeError("Unexpected app state: want to go back but can't")
RuntimeError: Unexpected app state: want to go back but can't

[09/15 18:59:11] Crash saved as "crashes/Crash-2022-09-15-18-59-11.zip".
[09/15 18:59:11] Please attach this file if you gonna report the crash at
[09/15 18:59:11] https://github.com/alexal1/Insomniac/issues

[09/15 18:59:11] Close Instagram app com.instagram.android

If you like this bot, please give us a star:
https://github.com/alexal1/Insomniac

Completed sessions: 0
Total duration: 0:00:00
Total interactions: 0
Successful interactions: 0
Total followed : 0
Total likes: 0
Total unfollowed: 0
Total stories watches: 0
Total comments: 0
Total get-profile: 0
Total scraped: 0
Removed mass followers: none

**Comment by thomaslc66** [comment]
Dude I was wondering if I wanted to pay using the patreon and then I try to launch this tool and it seems it's not working anymore. Everything is fucked up, version of instagram is almost banned to be used on some android phone, Memu doesn't support it anymore. Smell like somebody is leaving the ship

**Comment by alexal1** [comment]
@thomaslc66 Memu is not supporting any apk except for google play installation, don't know why. Let me know if you find a solution for any IG apk. "version of instagram is almost banned" how's that?
