### ISSUE TITLE
Error - module 'uiautomator2' has no attribute 'JSONRPCError'

### ISSUE THREAD

**Issue by codeclinic** [alexal1/Insomniac#444]
I keep getting the following error. It happens almost every session (possibly all sessions).

Here are a few crash logs:
[Crash-2022-09-20-17-10-30.zip](https://github.com/alexal1/Insomniac/files/9608969/Crash-2022-09-20-17-10-30.zip)
[Crash-2022-09-20-16-32-56.zip](https://github.com/alexal1/Insomniac/files/9608970/Crash-2022-09-20-16-32-56.zip)
[Crash-2022-09-20-15-59-06.zip](https://github.com/alexal1/Insomniac/files/9608971/Crash-2022-09-20-15-59-06.zip)
[Crash-2022-09-20-15-27-00.zip](https://github.com/alexal1/Insomniac/files/9608972/Crash-2022-09-20-15-27-00.zip)
[Crash-2022-09-20-11-30-46.zip](https://github.com/alexal1/Insomniac/files/9608973/Crash-2022-09-20-11-30-46.zip)
[Crash-2022-09-20-09-33-13.zip](https://github.com/alexal1/Insomniac/files/9608974/Crash-2022-09-20-09-33-13.zip)
[Crash-2022-09-20-09-04-13.zip](https://github.com/alexal1/Insomniac/files/9608975/Crash-2022-09-20-09-04-13.zip)
[Crash-2022-09-20-08-45-52.zip](https://github.com/alexal1/Insomniac/files/9608976/Crash-2022-09-20-08-45-52.zip)
[Crash-2022-09-20-08-26-18.zip](https://github.com/alexal1/Insomniac/files/9608977/Crash-2022-09-20-08-26-18.zip)
[Crash-2022-09-20-04-33-06.zip](https://github.com/alexal1/Insomniac/files/9608978/Crash-2022-09-20-04-33-06.zip)
[Crash-2022-09-20-04-13-19.zip](https://github.com/alexal1/Insomniac/files/9608979/Crash-2022-09-20-04-13-19.zip)

[09/20 17:10:30] Error - module 'uiautomator2' has no attribute 'JSONRPCError'
Traceback (most recent call last):
  File "C:\Users\phill\.pyenv\pyenv-win\versions\3.10.7\lib\site-packages\insomniac\device_facade.py", line 537, in scroll
    self.viewV2.scroll.toEnd(max_swipes=1)
  File "C:\Users\phill\.pyenv\pyenv-win\versions\3.10.7\lib\site-packages\uiautomator2\session.py", line 1196, in __call__
    return jsonrpc.scrollToEnd(selector, self.vertical,
  File "C:\Users\phill\.pyenv\pyenv-win\versions\3.10.7\lib\site-packages\uiautomator2\__init__.py", line 546, in __call__
    return self.server.jsonrpc_retry_call(self.method, params,
  File "C:\Users\phill\.pyenv\pyenv-win\versions\3.10.7\lib\site-packages\uiautomator2\__init__.py", line 553, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "C:\Users\phill\.pyenv\pyenv-win\versions\3.10.7\lib\site-packages\uiautomator2\__init__.py", line 645, in jsonrpc_call
    raise err
uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=android.widget.ListView, RESOURCE_ID=android:id/list], method: scrollToEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insomniac/extra_features/session.py", line 277, in run
  File "C:\Users\phill\.pyenv\pyenv-win\versions\3.10.7\lib\site-packages\insomniac\action_runners\interact\__init__.py", line 203, in run
    job()
  File "C:\Users\phill\.pyenv\pyenv-win\versions\3.10.7\lib\site-packages\insomniac\safely_runner.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\phill\.pyenv\pyenv-win\versions\3.10.7\lib\site-packages\insomniac\action_runners\interact\__init__.py", line 151, in job
    handle_blogger(device_wrapper.get(),
  File "C:\Users\phill\.pyenv\pyenv-win\versions\3.10.7\lib\site-packages\insomniac\action_runners\interact\action_handle_blogger.py", line 234, in handle_blogger
    followers_following_list_view.iterate_over_followers(is_myself, interact_with_follower, pre_conditions)
  File "C:\Users\phill\.pyenv\pyenv-win\versions\3.10.7\lib\site-packages\insomniac\views.py", line 1502, in iterate_over_followers
    list_view.scroll(DeviceFacade.Direction.BOTTOM)
  File "C:\Users\phill\.pyenv\pyenv-win\versions\3.10.7\lib\site-packages\insomniac\device_facade.py", line 538, in scroll
    except uiautomator2.JSONRPCError as e:
AttributeError: module 'uiautomator2' has no attribute 'JSONRPCError'

**Comment by evanpoliquin** [comment]
I'm having the same issue on Linux Mint. Installed everything correctly and have no crashes using the same interaction.json file on Windows. Any help or explanation would be super appreciated! @alexal1 
[Crash-2022-10-03-13-22-59.zip](https://github.com/alexal1/Insomniac/files/9699589/Crash-2022-10-03-13-22-59.zip)

**Comment by giobbepelle** [comment]
Error - module 'uiautomator2' has no attribute 'JSONRPCError'
Traceback (most recent call last):
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/device_facade.py", line 537, in scroll
    self.viewV2.scroll.toEnd(max_swipes=1)
  File "/home/giobbe/.local/lib/python3.10/site-packages/uiautomator2/session.py", line 1196, in __call__
    return jsonrpc.scrollToEnd(selector, self.vertical,
  File "/home/giobbe/.local/lib/python3.10/site-packages/uiautomator2/__init__.py", line 546, in __call__
    return self.server.jsonrpc_retry_call(self.method, params,
  File "/home/giobbe/.local/lib/python3.10/site-packages/uiautomator2/__init__.py", line 553, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "/home/giobbe/.local/lib/python3.10/site-packages/uiautomator2/__init__.py", line 645, in jsonrpc_call
    raise err
uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=android.widget.ListView, RESOURCE_ID=android:id/list], method: scrollToEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/session.py", line 361, in run
    action_runner.run(device_wrapper,
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/action_runners/interact/__init__.py", line 203, in run
    job()
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/safely_runner.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/action_runners/interact/__init__.py", line 151, in job
    handle_blogger(device_wrapper.get(),
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/action_runners/interact/action_handle_blogger.py", line 234, in handle_blogger
    followers_following_list_view.iterate_over_followers(is_myself, interact_with_follower, pre_conditions)
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/views.py", line 1502, in iterate_over_followers
    list_view.scroll(DeviceFacade.Direction.BOTTOM)
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/device_facade.py", line 538, in scroll
    except uiautomator2.JSONRPCError as e:
AttributeError: module 'uiautomator2' has no attribute 'JSONRPCError'

I have a similar problem
