### ISSUE TITLE
Error - module 'uiautomator2' has no attribute 'JSONRPCError'  --- ubuntu

### ISSUE THREAD

**Issue by giobbepelle** [alexal1/Insomniac#445]
Why?

Error - module 'uiautomator2' has no attribute 'JSONRPCError'
Traceback (most recent call last):
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/device_facade.py", line 537, in scroll
    self.viewV2.scroll.toEnd(max_swipes=1)
  File "/home/giobbe/.local/lib/python3.10/site-packages/uiautomator2/session.py", line 1196, in __call__
    return jsonrpc.scrollToEnd(selector, self.vertical,
  File "/home/giobbe/.local/lib/python3.10/site-packages/uiautomator2/__init__.py", line 546, in __call__
    return self.server.jsonrpc_retry_call(self.method, params,
  File "/home/giobbe/.local/lib/python3.10/site-packages/uiautomator2/__init__.py", line 553, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "/home/giobbe/.local/lib/python3.10/site-packages/uiautomator2/__init__.py", line 645, in jsonrpc_call
    raise err
uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=android.widget.ListView, RESOURCE_ID=android:id/list], method: scrollToEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/session.py", line 361, in run
    action_runner.run(device_wrapper,
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/action_runners/interact/__init__.py", line 203, in run
    job()
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/safely_runner.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/action_runners/interact/__init__.py", line 151, in job
    handle_blogger(device_wrapper.get(),
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/action_runners/interact/action_handle_blogger.py", line 234, in handle_blogger
    followers_following_list_view.iterate_over_followers(is_myself, interact_with_follower, pre_conditions)
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/views.py", line 1502, in iterate_over_followers
    list_view.scroll(DeviceFacade.Direction.BOTTOM)
  File "/home/giobbe/.local/lib/python3.10/site-packages/insomniac/device_facade.py", line 538, in scroll
    except uiautomator2.JSONRPCError as e:
AttributeError: module 'uiautomator2' has no attribute 'JSONRPCError'

**Comment by giobbepelle** [comment]
Alone I controll the problem!!

**Comment by Louis-de-Bontin** [comment]
> Alone I controll the problem!!

How ?
