### ISSUE TITLE
PLEASE HELP zlib.error: Error

### ISSUE THREAD

**Issue by adamazawi** [alexal1/Insomniac#454]
Hello
I know its so hard to get to have someone answer on here but please I need help with this error please, what do I need to do to fix it

Engine v3.8.6

[10/05 08:22:29] Your activation code is confirmed, welcome!
Traceback (most recent call last):
  File "C:\Users\12146\Desktop\Instagram\[start.py](http://start.py/)", line 4, in <module>
    [insomniac.run](http://insomniac.run/)(activation_code)
  File "C:\Users\12146\AppData\Local\Programs\Python\Python310\lib\site-packages\insomniac\__init__.py", line 30, in run
    from insomniac.extra_features.session import get_insomniac_extended_features_session
  File "C:\Users\12146\AppData\Local\Programs\Python\Python310\lib\site-packages\insomniac\extra_features\[session.py](http://session.py/)", line 3, in <module>
    exec(activation_controller.get_extra_feature('session'))
  File "C:\Users\12146\AppData\Local\Programs\Python\Python310\lib\site-packages\insomniac\[activation.py](http://activation.py/)", line 46, in get_extra_feature
    extra_feature = base64.b64decode(zlib.decompress(body))
zlib.error: Error -3 while decompressing data: incorrect header check

**Comment by adamazawi** [comment]
can someone respond plz
