### ISSUE TITLE
Error when i try to interact and get soft ban

### ISSUE THREAD

**Issue by nafferro** [alexal1/Insomniac#53]
i get this error: 

```
Traceback (most recent call last):
  File "insomniac.py", line 331, in wrapper
    func(*args, **kwargs)
  File "insomniac.py", line 149, in job
    on_interaction)
  File "/home/pi/Insomniac/src/action_handle_blogger.py", line 32, in handle_blogger
    _iterate_over_followers(device, interaction, storage, on_interaction, is_myself)
  File "/home/pi/Insomniac/src/action_handle_blogger.py", line 104, in _iterate_over_followers
    className='android.widget.LinearLayout'):
  File "/usr/local/lib/python3.6/site-packages/uiautomator/__init__.py", line 1222, in next
    return obj[self.index]
  File "/usr/local/lib/python3.6/site-packages/uiautomator/__init__.py", line 1203, in getitem
    raise IndexError()
IndexError
```

**Comment by alexal1** [comment]
Please try on this branch https://github.com/alexal1/Insomniac/tree/fix_index_error.
If it is ok, I'll merge it
