### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by M3GABOY** [alexal1/Insomniac#59]
```
Traceback (most recent call last):
  File "insomniac.py", line 335, in <module>
    main()
  File "insomniac.py", line 91, in main
    int(args.follow_limit),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by Eimuex** [comment]
Yup, same.

**Comment by alexal1** [comment]
What is your launch command?

**Comment by alexal1** [comment]
Hmmm, it crashes at start? Doesn't work for me. What is your `python3 --version`?

**Comment by Eimuex** [comment]
Yes, right after 'Hello username!' message. Python version 3.7.3

**Comment by alexal1** [comment]
Yeah, got it! Will fix now, thanks.
