### ISSUE TITLE
Crash (Spoken telegram)

### ISSUE THREAD

**Issue by DNUSH** [alexal1/Insomniac#70]
[07/28 12:03:43] Back to followers list
[07/28 12:03:44] Cannot get next item: probably reached end of the screen.
[07/28 12:03:44] Need to scroll now
[07/28 12:04:08] Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 438, in wrapper
    return _method_obj(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 135, in __call__
    "%s: %s" % (jsonresult["error"]["data"]["exceptionTypeName"], jsonresult["error"]["message"])
uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.ListView, RESOURCE_ID=android:id/list]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Insomniac/insomniac.py", line 295, in wrapper
    func(*args, **kwargs)
  File "/home/pi/Insomniac/insomniac.py", line 164, in job
    on_interaction)
  File "/home/pi/Insomniac/src/action_handle_blogger.py", line 37, in handle_blogger
    _iterate_over_followers(device, interaction, is_follow_limit_reached, storage, on_interaction, is_myself)
  File "/home/pi/Insomniac/src/action_handle_blogger.py", line 153, in _iterate_over_followers
    list_view.scroll.toEnd(max_swipes=1)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 76, in __call__
    return self.func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 1325, in _scroll
    return __scroll_to_end(vertical, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 1310, in __scroll_to_end
    return self.jsonrpc.scrollToEnd(self.selector, vertical, max_swipes, steps)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 458, in wrapper
    return _method_obj(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 135, in __call__
    "%s: %s" % (jsonresult["error"]["data"]["exceptionTypeName"], jsonresult["error"]["message"])
uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.ListView, RESOURCE_ID=android:id/list]

[07/28 12:04:08] Screenshot taken and saved as Crash-2020-07-28-12-04-08.png
[07/28 12:04:08] No idea what it was. Let's try again.
[07/28 12:04:08] Close Instagram app
[07/28 12:04:09] Sleep for 2 seconds
[07/28 12:04:11] Open Instagram app
[07/28 12:04:12] Sleep for 4 seconds
[07/28 12:04:16] Press profile
[07/28 12:04:24] Press search
[07/28 12:04:30] Open user @memegame.ok
[07/28 12:04:37] Open @memegame.ok followers
[07/28 12:04:43] Iterate over visible followers
[07/28 12:04:43] No followers were iterated, finish.
[07/28 12:04:43] Close Instagram app

![Crash-2020-07-28-12-04-08](https://user-images.githubusercontent.com/44299707/88719232-ee7b2e00-d0f0-11ea-8c5e-4cb7b5c53491.png)

**Comment by alexal1** [comment]
So the script thinks that it's on followers list, but actually it's still on someone's profile. Didn't you mention something strange in its behavior? Maybe some wrong screen was opened before?

**Comment by alexal1** [comment]
Probably fixed in `v2.0.0`, please reopen if it's not.
