### ISSUE TITLE
Stalls on Press profile

### ISSUE THREAD

**Issue by cryptocxeq** [alexal1/Insomniac#82]
-------- START: 2020-08-14 21:08:47.353789 --------
[08/14 21:08:47] Open Instagram app
[08/14 21:08:48] Sleep for 3 seconds
[08/14 21:08:51] Press profile

Hangs forever there...

Trying to run it on a s5

**Comment by cryptocxeq** [comment]
I tried on s10 too and did the same thing

**Comment by cryptocxeq** [comment]
except in s10 says

[08/14 21:35:28] Open Instagram app
Warning: Activity not started, intent has been delivered to currently running top-most instance.
[08/14 21:35:28] Sleep for 2 seconds
[08/14 21:35:30] Press profile

**Comment by Eimuex** [comment]
Yes, same problem.

**Comment by alexal1** [comment]
Seems that Instagram started UI update. Please try on this branch guys #85

**Comment by Eimuex** [comment]
[08/16 14:27:14] Open Instagram app
[08/16 14:27:14] Sleep for 2 seconds
[08/16 14:27:16] Press profile
[08/16 14:27:17] Standard way of navigation failed, trying another one...
[08/16 14:27:17] Cannot find profile button. Switch to English please.
Traceback (most recent call last):
  File "insomniac.py", line 421, in <module>
    main()
  File "insomniac.py", line 93, in main
    session_state.my_following_count = get_my_profile_info(device)
  File "/home/pi/Insomniac-fix_navigation_on_some_devices/src/action_get_my_profile_info.py", line 8, in get_my_profile_info
    navigate(device, Tabs.PROFILE)
  File "/home/pi/Insomniac-fix_navigation_on_some_devices/src/navigation.py", line 13, in navigate
    _navigate_alternative(device, tab)
  File "/home/pi/Insomniac-fix_navigation_on_some_devices/src/navigation.py", line 38, in _navigate_alternative
    raise NavigationException("Cannot find " + tab_name + " button.")
src.navigation.NavigationException: Cannot find profile button.

**Comment by Eimuex** [comment]
When I tried second time just stalls like before

**Comment by cryptocxeq** [comment]
I experienced no difference I think

**Comment by alexal1** [comment]
@Eimuex did you switch to English locale?

**Comment by Eimuex** [comment]
@alexal1 Everything is in English since I started using Insomniac

**Comment by alexal1** [comment]
> That's on version 1.9.0

Actually there's no difference on which version you'll try it. It's some Instagram update that broke the logic.

**Comment by alexal1** [comment]
We've found out that migration to **uiautomator2** library will fix this problem. Please wait a couple of days, soon the script will work perfectly.

**Comment by cryptocxeq** [comment]
thanks alexal1

**Comment by antonrifco** [comment]
@alexal1 should we uninstall the uiautomator ? or both lib can stay?

**Comment by alexal1** [comment]
@antonrifco both can stay, I'll update README when update comes

**Comment by ketwong** [comment]
For a quick fix, uninstall instagram and install an older version of instagram like 3-5 version behind of current version now.

**Comment by cryptocxeq** [comment]
i did try that on my device with 148 and 100 and neither worked but ymmv
