### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by flodes80** [alexal1/Insomniac#89]
Hi,

There is a scrolling issue that happen often in a session (about 6/7 times).
Here is the logs:

`[08/23 07:47:25] Session progress: 142 likes, 47 followed, 68 successful interactions for @noeloquence
[08/23 07:47:25] Back to followers list
[08/23 07:47:27] Next item not found: probably reached end of the screen.
[08/23 07:47:27] Need to scroll now
[08/23 07:47:38] Traceback (most recent call last):
  File "/home/pi/Insomniac/insomniac.py", line 399, in wrapper
    func(*args, **kwargs)
  File "/home/pi/Insomniac/insomniac.py", line 208, in job
    on_interaction)
  File "/home/pi/Insomniac/src/action_handle_blogger.py", line 39, in handle_blogger
    _iterate_over_followers(device, interaction, is_follow_limit_reached, storage, on_interaction, is_myself)
  File "/home/pi/Insomniac/src/action_handle_blogger.py", line 159, in _iterate_over_followers
    list_view.scroll.toEnd(max_swipes=1)
  File "/usr/local/lib/python3.7/dist-packages/uiautomator2/_selector.py", line 575, in __call__
    max_swipes, steps)
  File "/usr/local/lib/python3.7/dist-packages/uiautomator2/__init__.py", line 435, in __call__
    http_timeout)
  File "/usr/local/lib/python3.7/dist-packages/uiautomator2/__init__.py", line 441, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/uiautomator2/__init__.py", line 513, in _jsonrpc_call
    raise err
uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=android.widget.ListView, RESOURCE_ID=android:id/list], method: scrollToEnd`

I attach some screenshot too:
![Crash-2020-08-23-07-15-59](https://user-images.githubusercontent.com/12677853/90974436-7eaf6600-e52b-11ea-93c8-770e1ee5cd40.png)
![Crash-2020-08-23-07-08-34](https://user-images.githubusercontent.com/12677853/90974438-7fe09300-e52b-11ea-8b6b-2444293b388f.png)

**It seems to be related to pinned stories from users. It takes some place and uiautomator2 can't find the list that is searching for**

**Comment by alexal1** [comment]
Could you please provide a full log in a txt file?

**Comment by gvmturl** [comment]
Is it solved?

**Comment by alexal1** [comment]
🤷‍♂️
I think we can close it as there's not enough info. If someone reopens it, please attach crash info.
