### ISSUE TITLE
Need to scroll now

### ISSUE THREAD

**Issue by Orezhon** [alexal1/Insomniac#94]
The script always crashes when it displays: "Need to scroll now"

[08/26 21:09:43] Next item not found: probably reached end of the screen.
[08/26 21:09:43] Need to scroll now
[08/26 21:09:55] Traceback (most recent call last):
  File "insomniac.py", line 379, in wrapper
    func(*args, **kwargs)
  File "insomniac.py", line 191, in job
    on_interaction)
  File "/home/pi/Insomniac/src/action_handle_blogger.py", line 39, in handle_blogger
    _iterate_over_followers(device, interaction, is_follow_limit_reached, storage, on_interaction, is_myself)
  File "/home/pi/Insomniac/src/action_handle_blogger.py", line 159, in _iterate_over_followers
    list_view.scroll.toEnd(max_swipes=1)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/_selector.py", line 575, in __call__
    max_swipes, steps)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 435, in __call__
    http_timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 441, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator2/__init__.py", line 513, in _jsonrpc_call
    raise err
uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[CLASS=android.widget.ListView, RESOURCE_ID=android:id/list], method: scrollToEnd

**Comment by Orezhon** [comment]
Log in attached
[log.txt](https://github.com/alexal1/Insomniac/files/5132425/log.txt)

**Comment by alexal1** [comment]
> The script always crashes when it displays: "Need to scroll now"

As I see by logs it crashes only after second time it writes this. Any idea what's the difference?

**Comment by alexal1** [comment]
If this didn't happen before, then maybe there are some problems with device connection? As I see in logs, there's "HTTPConnectionPool(host='localhost', port=42723): Read timed out. (read timeout=10)". Have you already tried these advices https://www.patreon.com/posts/problems-with-to-38702683?

**Comment by Orezhon** [comment]
> If this didn't happen before, then maybe there are some problems with device connection? As I see in logs, there's "HTTPConnectionPool(host='localhost', port=42723): Read timed out. (read timeout=10)". Have you already tried these advices https://www.patreon.com/posts/problems-with-to-38702683?


I tested on Raspberry and Windows, with different USB ports, and with different cables. The result is always the same, the first or second time of "need to scroll" crashes (always).

The script worked fine for me for months before the latest version.

**Comment by alexal1** [comment]
Ok, got it.
Please try on this branch #95.
If we don't find solution, I will simply add possibility to the script to work on uiautomator1 as before.

**Comment by alexal1** [comment]
Please try with the `--old` flag to run it on the old version of `uiautomator`.
